# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.models.timeseries_point import TimeseriesPoint

class TestTimeseriesPoint(unittest.TestCase):
    """TimeseriesPoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimeseriesPoint:
        """Test TimeseriesPoint
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimeseriesPoint`
        """
        model = TimeseriesPoint()
        if include_optional:
            return TimeseriesPoint(
                var_date = '',
                cost = 1.337
            )
        else:
            return TimeseriesPoint(
                var_date = '',
                cost = 1.337,
        )
        """

    def testTimeseriesPoint(self):
        """Test TimeseriesPoint"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
