# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.models.library_in import LibraryIn

class TestLibraryIn(unittest.TestCase):
    """LibraryIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LibraryIn:
        """Test LibraryIn
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LibraryIn`
        """
        model = LibraryIn()
        if include_optional:
            return LibraryIn(
                name = '',
                description = ''
            )
        else:
            return LibraryIn(
                name = '',
        )
        """

    def testLibraryIn(self):
        """Test LibraryIn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
