# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.models.cost_by_source import CostBySource

class TestCostBySource(unittest.TestCase):
    """CostBySource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CostBySource:
        """Test CostBySource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CostBySource`
        """
        model = CostBySource()
        if include_optional:
            return CostBySource(
                source = '',
                total_cost = 1.337,
                total_tokens = 56,
                prompt_tokens = 56,
                completion_tokens = 56,
                record_count = 56
            )
        else:
            return CostBySource(
                source = '',
                total_cost = 1.337,
                total_tokens = 56,
                prompt_tokens = 56,
                completion_tokens = 56,
                record_count = 56,
        )
        """

    def testCostBySource(self):
        """Test CostBySource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
