# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.models.tenant_theme_out import TenantThemeOut

class TestTenantThemeOut(unittest.TestCase):
    """TenantThemeOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantThemeOut:
        """Test TenantThemeOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantThemeOut`
        """
        model = TenantThemeOut()
        if include_optional:
            return TenantThemeOut(
                name = '',
                slug = '',
                domain = '',
                timezone = '',
                locale = '',
                display_name = '',
                motto = '',
                logo_url = '',
                square_logo_url = '',
                favicon_url = '',
                chat_square_logo_url = '',
                primary_color = '',
                secondary_color = '',
                theme = ''
            )
        else:
            return TenantThemeOut(
                name = '',
                slug = '',
                timezone = '',
                locale = '',
        )
        """

    def testTenantThemeOut(self):
        """Test TenantThemeOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
