# coding: utf-8

"""
    Neuland AI Hub API

    The **Neuland AI Hub API** powers chat, retrieval-augmented document Q&A, assistants, and the surrounding workspace, tenant, and integration features of the platform.  Most endpoints require authentication. Obtain a token via the **Auth** endpoints (or use an **ApiKey**) and send it as a bearer token in the `Authorization` header.  Endpoints are grouped by resource — see the tag groups below.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from neuland_hub_sdk.models.connector_auth_type import ConnectorAuthType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConnectorStatusOut(BaseModel):
    """
    ConnectorStatusOut
    """ # noqa: E501
    connector_id: StrictInt = Field(description="Internal id of the connector (deprecated; use connector_public_id).")
    connector_public_id: UUID = Field(description="Public id of the connector. Use it for the consent, credential, and config endpoints (which are keyed by public id).")
    name: StrictStr = Field(description="Human-readable connector name.")
    auth_type: ConnectorAuthType = Field(description="Authentication mechanism the connector uses.")
    connected: StrictBool = Field(description="Whether the connector is fully usable for the caller (consent granted and all required config present).")
    needs_consent: StrictBool = Field(description="OAuth authorization is required before the connector can be used.")
    needs_config: StrictBool = Field(description="An admin credential template part is required but not yet set.")
    needs_user_config: StrictBool = Field(description="A per-user credential template part is required but not yet set.")
    has_admin_config: StrictBool = Field(description="The connector has an admin-managed credential part.")
    missing_caps: List[Optional[StrictStr]] = Field(description="Capabilities not yet granted; empty unless consent is needed.")
    __properties: ClassVar[List[str]] = ["connector_id", "connector_public_id", "name", "auth_type", "connected", "needs_consent", "needs_config", "needs_user_config", "has_admin_config", "missing_caps"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConnectorStatusOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConnectorStatusOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "connector_id": obj.get("connector_id"),
            "connector_public_id": obj.get("connector_public_id"),
            "name": obj.get("name"),
            "auth_type": obj.get("auth_type"),
            "connected": obj.get("connected"),
            "needs_consent": obj.get("needs_consent"),
            "needs_config": obj.get("needs_config"),
            "needs_user_config": obj.get("needs_user_config"),
            "has_admin_config": obj.get("has_admin_config"),
            "missing_caps": obj.get("missing_caps")
        })
        return _obj


