# coding: utf-8

"""
    Neuland AI Hub API

    The **Neuland AI Hub API** powers chat, retrieval-augmented document Q&A, assistants, and the surrounding workspace, tenant, and integration features of the platform.  Most endpoints require authentication. Obtain a token via the **Auth** endpoints (or use an **ApiKey**) and send it as a bearer token in the `Authorization` header.  Endpoints are grouped by resource — see the tag groups below.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Document(BaseModel):
    """
    Document
    """ # noqa: E501
    id: Optional[StrictInt] = None
    created_at: Optional[datetime] = Field(default=None, description="Timestamp when the document was created.")
    updated_at: Optional[datetime] = Field(default=None, description="Timestamp when the document was last updated.")
    creator_user_id: StrictInt
    tenant_id: StrictInt
    project_id: Optional[StrictInt]
    chat_id: Optional[StrictInt]
    assistant_id: Optional[StrictInt] = None
    message_id: Optional[StrictInt] = None
    library_id: Optional[StrictInt] = None
    filename: StrictStr = Field(description="Original filename of the document.")
    content_type: Optional[StrictStr] = Field(default='text/plain', description="MIME content type of the document.")
    description: Optional[StrictStr]
    content_id: Optional[StrictInt] = None
    src: Optional[StrictStr]
    url: Optional[StrictStr]
    sp_site_id: Optional[StrictStr]
    sp_drive_id: Optional[StrictStr]
    sp_drive_item_id: Optional[StrictStr]
    sp_parent_folder_id: Optional[StrictStr]
    sp_parent_path: Optional[StrictStr]
    sp_last_modified_date_time: Optional[datetime]
    sp_import_folder_id: Optional[StrictStr]
    autosync: Optional[StrictBool]
    import_token: Optional[UUID]
    import_started_at: Optional[datetime]
    import_finished_at: Optional[datetime]
    import_error: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "created_at", "updated_at", "creator_user_id", "tenant_id", "project_id", "chat_id", "assistant_id", "message_id", "library_id", "filename", "content_type", "description", "content_id", "src", "url", "sp_site_id", "sp_drive_id", "sp_drive_item_id", "sp_parent_folder_id", "sp_parent_path", "sp_last_modified_date_time", "sp_import_folder_id", "autosync", "import_token", "import_started_at", "import_finished_at", "import_error"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Document from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if project_id (nullable) is None
        # and model_fields_set contains the field
        if self.project_id is None and "project_id" in self.model_fields_set:
            _dict['project_id'] = None

        # set to None if chat_id (nullable) is None
        # and model_fields_set contains the field
        if self.chat_id is None and "chat_id" in self.model_fields_set:
            _dict['chat_id'] = None

        # set to None if assistant_id (nullable) is None
        # and model_fields_set contains the field
        if self.assistant_id is None and "assistant_id" in self.model_fields_set:
            _dict['assistant_id'] = None

        # set to None if message_id (nullable) is None
        # and model_fields_set contains the field
        if self.message_id is None and "message_id" in self.model_fields_set:
            _dict['message_id'] = None

        # set to None if library_id (nullable) is None
        # and model_fields_set contains the field
        if self.library_id is None and "library_id" in self.model_fields_set:
            _dict['library_id'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if content_id (nullable) is None
        # and model_fields_set contains the field
        if self.content_id is None and "content_id" in self.model_fields_set:
            _dict['content_id'] = None

        # set to None if src (nullable) is None
        # and model_fields_set contains the field
        if self.src is None and "src" in self.model_fields_set:
            _dict['src'] = None

        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        # set to None if sp_site_id (nullable) is None
        # and model_fields_set contains the field
        if self.sp_site_id is None and "sp_site_id" in self.model_fields_set:
            _dict['sp_site_id'] = None

        # set to None if sp_drive_id (nullable) is None
        # and model_fields_set contains the field
        if self.sp_drive_id is None and "sp_drive_id" in self.model_fields_set:
            _dict['sp_drive_id'] = None

        # set to None if sp_drive_item_id (nullable) is None
        # and model_fields_set contains the field
        if self.sp_drive_item_id is None and "sp_drive_item_id" in self.model_fields_set:
            _dict['sp_drive_item_id'] = None

        # set to None if sp_parent_folder_id (nullable) is None
        # and model_fields_set contains the field
        if self.sp_parent_folder_id is None and "sp_parent_folder_id" in self.model_fields_set:
            _dict['sp_parent_folder_id'] = None

        # set to None if sp_parent_path (nullable) is None
        # and model_fields_set contains the field
        if self.sp_parent_path is None and "sp_parent_path" in self.model_fields_set:
            _dict['sp_parent_path'] = None

        # set to None if sp_last_modified_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.sp_last_modified_date_time is None and "sp_last_modified_date_time" in self.model_fields_set:
            _dict['sp_last_modified_date_time'] = None

        # set to None if sp_import_folder_id (nullable) is None
        # and model_fields_set contains the field
        if self.sp_import_folder_id is None and "sp_import_folder_id" in self.model_fields_set:
            _dict['sp_import_folder_id'] = None

        # set to None if autosync (nullable) is None
        # and model_fields_set contains the field
        if self.autosync is None and "autosync" in self.model_fields_set:
            _dict['autosync'] = None

        # set to None if import_token (nullable) is None
        # and model_fields_set contains the field
        if self.import_token is None and "import_token" in self.model_fields_set:
            _dict['import_token'] = None

        # set to None if import_started_at (nullable) is None
        # and model_fields_set contains the field
        if self.import_started_at is None and "import_started_at" in self.model_fields_set:
            _dict['import_started_at'] = None

        # set to None if import_finished_at (nullable) is None
        # and model_fields_set contains the field
        if self.import_finished_at is None and "import_finished_at" in self.model_fields_set:
            _dict['import_finished_at'] = None

        # set to None if import_error (nullable) is None
        # and model_fields_set contains the field
        if self.import_error is None and "import_error" in self.model_fields_set:
            _dict['import_error'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Document from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "creator_user_id": obj.get("creator_user_id"),
            "tenant_id": obj.get("tenant_id"),
            "project_id": obj.get("project_id"),
            "chat_id": obj.get("chat_id"),
            "assistant_id": obj.get("assistant_id"),
            "message_id": obj.get("message_id"),
            "library_id": obj.get("library_id"),
            "filename": obj.get("filename"),
            "content_type": obj.get("content_type") if obj.get("content_type") is not None else 'text/plain',
            "description": obj.get("description"),
            "content_id": obj.get("content_id"),
            "src": obj.get("src"),
            "url": obj.get("url"),
            "sp_site_id": obj.get("sp_site_id"),
            "sp_drive_id": obj.get("sp_drive_id"),
            "sp_drive_item_id": obj.get("sp_drive_item_id"),
            "sp_parent_folder_id": obj.get("sp_parent_folder_id"),
            "sp_parent_path": obj.get("sp_parent_path"),
            "sp_last_modified_date_time": obj.get("sp_last_modified_date_time"),
            "sp_import_folder_id": obj.get("sp_import_folder_id"),
            "autosync": obj.get("autosync"),
            "import_token": obj.get("import_token"),
            "import_started_at": obj.get("import_started_at"),
            "import_finished_at": obj.get("import_finished_at"),
            "import_error": obj.get("import_error")
        })
        return _obj


