# coding: utf-8

"""
    Neuland AI Hub API

    The **Neuland AI Hub API** powers chat, retrieval-augmented document Q&A, assistants, and the surrounding workspace, tenant, and integration features of the platform.  Most endpoints require authentication. Obtain a token via the **Auth** endpoints (or use an **ApiKey**) and send it as a bearer token in the `Authorization` header.  Endpoints are grouped by resource — see the tag groups below.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InvitationOut(BaseModel):
    """
    InvitationOut
    """ # noqa: E501
    id: StrictInt = Field(description="Unique identifier of the invitation.")
    public_id: UUID = Field(description="Public, non-enumerable external identifier of the invitation.")
    email: StrictStr = Field(description="Email address the invitation was sent to.")
    tenant_id: StrictInt = Field(description="Internal id of the tenant (deprecated; use tenant_public_id).")
    tenant_public_id: Optional[UUID] = None
    project_id: Optional[StrictInt]
    project_public_id: Optional[UUID] = None
    status: StrictStr = Field(description="Current invitation status.")
    created_at: datetime = Field(description="UTC timestamp when the invitation was created.")
    accepted_at: Optional[datetime]
    revoked_at: Optional[datetime]
    creator_user_id: StrictInt = Field(description="Internal id of the creating user (deprecated; use creator_user_public_id).")
    creator_user_public_id: Optional[UUID] = None
    __properties: ClassVar[List[str]] = ["id", "public_id", "email", "tenant_id", "tenant_public_id", "project_id", "project_public_id", "status", "created_at", "accepted_at", "revoked_at", "creator_user_id", "creator_user_public_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvitationOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if tenant_public_id (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_public_id is None and "tenant_public_id" in self.model_fields_set:
            _dict['tenant_public_id'] = None

        # set to None if project_id (nullable) is None
        # and model_fields_set contains the field
        if self.project_id is None and "project_id" in self.model_fields_set:
            _dict['project_id'] = None

        # set to None if project_public_id (nullable) is None
        # and model_fields_set contains the field
        if self.project_public_id is None and "project_public_id" in self.model_fields_set:
            _dict['project_public_id'] = None

        # set to None if accepted_at (nullable) is None
        # and model_fields_set contains the field
        if self.accepted_at is None and "accepted_at" in self.model_fields_set:
            _dict['accepted_at'] = None

        # set to None if revoked_at (nullable) is None
        # and model_fields_set contains the field
        if self.revoked_at is None and "revoked_at" in self.model_fields_set:
            _dict['revoked_at'] = None

        # set to None if creator_user_public_id (nullable) is None
        # and model_fields_set contains the field
        if self.creator_user_public_id is None and "creator_user_public_id" in self.model_fields_set:
            _dict['creator_user_public_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvitationOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "public_id": obj.get("public_id"),
            "email": obj.get("email"),
            "tenant_id": obj.get("tenant_id"),
            "tenant_public_id": obj.get("tenant_public_id"),
            "project_id": obj.get("project_id"),
            "project_public_id": obj.get("project_public_id"),
            "status": obj.get("status"),
            "created_at": obj.get("created_at"),
            "accepted_at": obj.get("accepted_at"),
            "revoked_at": obj.get("revoked_at"),
            "creator_user_id": obj.get("creator_user_id"),
            "creator_user_public_id": obj.get("creator_user_public_id")
        })
        return _obj


