# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Settings(BaseModel):
    """
    Settings
    """ # noqa: E501
    id: Optional[StrictInt] = None
    tenant_id: StrictInt
    default_llm_catalog_id: Optional[StrictInt] = None
    created_at: Optional[datetime] = None
    guardrails_enabled: Optional[StrictBool] = False
    sharepoint_enabled: Optional[StrictBool]
    inbound_guardrail: Optional[StrictStr] = None
    outbound_guardrail: Optional[StrictStr] = None
    system_prompt: Optional[StrictStr] = None
    inserted_by: Optional[StrictStr]
    errlog_webhook_url: Optional[StrictStr] = None
    default_language: Optional[Annotated[str, Field(strict=True, max_length=5)]] = 'en'
    require_email_confirmation: Optional[StrictBool] = False
    __properties: ClassVar[List[str]] = ["id", "tenant_id", "default_llm_catalog_id", "created_at", "guardrails_enabled", "sharepoint_enabled", "inbound_guardrail", "outbound_guardrail", "system_prompt", "inserted_by", "errlog_webhook_url", "default_language", "require_email_confirmation"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Settings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if default_llm_catalog_id (nullable) is None
        # and model_fields_set contains the field
        if self.default_llm_catalog_id is None and "default_llm_catalog_id" in self.model_fields_set:
            _dict['default_llm_catalog_id'] = None

        # set to None if sharepoint_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.sharepoint_enabled is None and "sharepoint_enabled" in self.model_fields_set:
            _dict['sharepoint_enabled'] = None

        # set to None if inbound_guardrail (nullable) is None
        # and model_fields_set contains the field
        if self.inbound_guardrail is None and "inbound_guardrail" in self.model_fields_set:
            _dict['inbound_guardrail'] = None

        # set to None if outbound_guardrail (nullable) is None
        # and model_fields_set contains the field
        if self.outbound_guardrail is None and "outbound_guardrail" in self.model_fields_set:
            _dict['outbound_guardrail'] = None

        # set to None if system_prompt (nullable) is None
        # and model_fields_set contains the field
        if self.system_prompt is None and "system_prompt" in self.model_fields_set:
            _dict['system_prompt'] = None

        # set to None if inserted_by (nullable) is None
        # and model_fields_set contains the field
        if self.inserted_by is None and "inserted_by" in self.model_fields_set:
            _dict['inserted_by'] = None

        # set to None if errlog_webhook_url (nullable) is None
        # and model_fields_set contains the field
        if self.errlog_webhook_url is None and "errlog_webhook_url" in self.model_fields_set:
            _dict['errlog_webhook_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Settings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "tenant_id": obj.get("tenant_id"),
            "default_llm_catalog_id": obj.get("default_llm_catalog_id"),
            "created_at": obj.get("created_at"),
            "guardrails_enabled": obj.get("guardrails_enabled") if obj.get("guardrails_enabled") is not None else False,
            "sharepoint_enabled": obj.get("sharepoint_enabled"),
            "inbound_guardrail": obj.get("inbound_guardrail"),
            "outbound_guardrail": obj.get("outbound_guardrail"),
            "system_prompt": obj.get("system_prompt"),
            "inserted_by": obj.get("inserted_by"),
            "errlog_webhook_url": obj.get("errlog_webhook_url"),
            "default_language": obj.get("default_language") if obj.get("default_language") is not None else 'en',
            "require_email_confirmation": obj.get("require_email_confirmation") if obj.get("require_email_confirmation") is not None else False
        })
        return _obj


