# coding: utf-8

"""
    Neuland AI Hub API

    The **Neuland AI Hub API** powers chat, retrieval-augmented document Q&A, assistants, and the surrounding workspace, tenant, and integration features of the platform.  Most endpoints require authentication. Obtain a token via the **Auth** endpoints (or use an **ApiKey**) and send it as a bearer token in the `Authorization` header.  Endpoints are grouped by resource — see the tag groups below.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Tag(BaseModel):
    """
    Tag
    """ # noqa: E501
    created_at: Optional[datetime] = Field(default=None, description="UTC timestamp when the record was created.")
    updated_at: Optional[datetime] = Field(default=None, description="UTC timestamp when the record was last updated.")
    id: Optional[StrictInt] = None
    tenant_id: StrictInt = Field(description="ID of the tenant that owns the tag.")
    name: Annotated[str, Field(strict=True, max_length=50)] = Field(description="Name of the tag.")
    creator_user_id: Optional[StrictInt] = None
    updater_user_id: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["created_at", "updated_at", "id", "tenant_id", "name", "creator_user_id", "updater_user_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Tag from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if creator_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.creator_user_id is None and "creator_user_id" in self.model_fields_set:
            _dict['creator_user_id'] = None

        # set to None if updater_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.updater_user_id is None and "updater_user_id" in self.model_fields_set:
            _dict['updater_user_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Tag from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "id": obj.get("id"),
            "tenant_id": obj.get("tenant_id"),
            "name": obj.get("name"),
            "creator_user_id": obj.get("creator_user_id"),
            "updater_user_id": obj.get("updater_user_id")
        })
        return _obj


