# coding: utf-8

"""
    Neuland AI Hub API

    The **Neuland AI Hub API** powers chat, retrieval-augmented document Q&A, assistants, and the surrounding workspace, tenant, and integration features of the platform.  Most endpoints require authentication. Obtain a token via the **Auth** endpoints (or use an **ApiKey**) and send it as a bearer token in the `Authorization` header.  Endpoints are grouped by resource — see the tag groups below.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from neuland_hub_sdk.models.tool_call_progress_step_out import ToolCallProgressStepOut
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ToolCallOut(BaseModel):
    """
    ToolCallOut
    """ # noqa: E501
    id: StrictInt = Field(description="ID of the tool call.")
    call_id: StrictStr = Field(description="Provider-assigned identifier for the tool call.")
    tool_name: StrictStr = Field(description="Name of the invoked tool.")
    call_group: StrictInt = Field(description="Group index for tool calls issued together.")
    call_index: StrictInt = Field(description="Order of the call within its group.")
    state: Optional[StrictStr]
    is_error: Optional[StrictBool]
    description: Optional[StrictStr]
    progress_steps: List[ToolCallProgressStepOut] = Field(description="Ordered progress steps emitted during the call.")
    __properties: ClassVar[List[str]] = ["id", "call_id", "tool_name", "call_group", "call_index", "state", "is_error", "description", "progress_steps"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ToolCallOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in progress_steps (list)
        _items = []
        if self.progress_steps:
            for _item_progress_steps in self.progress_steps:
                if _item_progress_steps:
                    _items.append(_item_progress_steps.to_dict())
            _dict['progress_steps'] = _items
        # set to None if state (nullable) is None
        # and model_fields_set contains the field
        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        # set to None if is_error (nullable) is None
        # and model_fields_set contains the field
        if self.is_error is None and "is_error" in self.model_fields_set:
            _dict['is_error'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ToolCallOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "call_id": obj.get("call_id"),
            "tool_name": obj.get("tool_name"),
            "call_group": obj.get("call_group"),
            "call_index": obj.get("call_index"),
            "state": obj.get("state"),
            "is_error": obj.get("is_error"),
            "description": obj.get("description"),
            "progress_steps": [ToolCallProgressStepOut.from_dict(_item) for _item in obj["progress_steps"]] if obj.get("progress_steps") is not None else None
        })
        return _obj


