# coding: utf-8

"""
    Neuland AI Hub API

    The **Neuland AI Hub API** powers chat, retrieval-augmented document Q&A, assistants, and the surrounding workspace, tenant, and integration features of the platform.  Most endpoints require authentication. Obtain a token via the **Auth** endpoints (or use an **ApiKey**) and send it as a bearer token in the `Authorization` header.  Endpoints are grouped by resource — see the tag groups below.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UserMeOut(BaseModel):
    """
    The current user's own profile (/users/me), extended with the effective feature-flag map for their tenant. Kept separate from ``UserOut`` so list endpoints don't resolve flags per row.
    """ # noqa: E501
    id: StrictInt = Field(description="Unique identifier of the user.")
    public_id: UUID = Field(description="Public, non-enumerable external identifier of the user.")
    created_at: datetime = Field(description="UTC timestamp when the user was created.")
    email: StrictStr = Field(description="Current confirmed email address.")
    email_confirmed: StrictBool = Field(description="Whether the email address has been confirmed.")
    pending_email: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    first_name: Optional[StrictStr] = None
    last_name: Optional[StrictStr] = None
    admin: Optional[StrictBool] = Field(default=False, description="Whether the user has tenant administrator privileges.")
    superadmin: Optional[StrictBool] = None
    active: StrictBool = Field(description="Whether the account is active and can authenticate.")
    tenant_id: Optional[StrictInt] = None
    tenant_public_id: Optional[UUID] = None
    permissions: Optional[List[StrictStr]] = Field(default=None, description="Effective permission keys the user holds, including those granted through group membership.")
    features: Optional[Dict[str, Optional[StrictBool]]] = Field(default=None, description="Effective feature-flag values for the user's tenant.")
    __properties: ClassVar[List[str]] = ["id", "public_id", "created_at", "email", "email_confirmed", "pending_email", "name", "first_name", "last_name", "admin", "superadmin", "active", "tenant_id", "tenant_public_id", "permissions", "features"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserMeOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if pending_email (nullable) is None
        # and model_fields_set contains the field
        if self.pending_email is None and "pending_email" in self.model_fields_set:
            _dict['pending_email'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if first_name (nullable) is None
        # and model_fields_set contains the field
        if self.first_name is None and "first_name" in self.model_fields_set:
            _dict['first_name'] = None

        # set to None if last_name (nullable) is None
        # and model_fields_set contains the field
        if self.last_name is None and "last_name" in self.model_fields_set:
            _dict['last_name'] = None

        # set to None if superadmin (nullable) is None
        # and model_fields_set contains the field
        if self.superadmin is None and "superadmin" in self.model_fields_set:
            _dict['superadmin'] = None

        # set to None if tenant_id (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_id is None and "tenant_id" in self.model_fields_set:
            _dict['tenant_id'] = None

        # set to None if tenant_public_id (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_public_id is None and "tenant_public_id" in self.model_fields_set:
            _dict['tenant_public_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserMeOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "public_id": obj.get("public_id"),
            "created_at": obj.get("created_at"),
            "email": obj.get("email"),
            "email_confirmed": obj.get("email_confirmed"),
            "pending_email": obj.get("pending_email"),
            "name": obj.get("name"),
            "first_name": obj.get("first_name"),
            "last_name": obj.get("last_name"),
            "admin": obj.get("admin") if obj.get("admin") is not None else False,
            "superadmin": obj.get("superadmin"),
            "active": obj.get("active"),
            "tenant_id": obj.get("tenant_id"),
            "tenant_public_id": obj.get("tenant_public_id"),
            "permissions": obj.get("permissions"),
            "features": obj.get("features")
        })
        return _obj


