# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from neuland_hub_sdk.models.o_auth2_provider_enum import OAuth2ProviderEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OAuthClient(BaseModel):
    """
    OAuthClient
    """ # noqa: E501
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    creator_user_id: Optional[StrictInt] = None
    updater_user_id: Optional[StrictInt] = None
    id: Optional[StrictInt] = None
    name: StrictStr
    provider_key: OAuth2ProviderEnum
    client_id: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    icon_url: Optional[StrictStr] = None
    authorize_url: StrictStr
    token_url: StrictStr
    redirect_uri: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["created_at", "updated_at", "creator_user_id", "updater_user_id", "id", "name", "provider_key", "client_id", "description", "icon_url", "authorize_url", "token_url", "redirect_uri"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OAuthClient from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if creator_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.creator_user_id is None and "creator_user_id" in self.model_fields_set:
            _dict['creator_user_id'] = None

        # set to None if updater_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.updater_user_id is None and "updater_user_id" in self.model_fields_set:
            _dict['updater_user_id'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if client_id (nullable) is None
        # and model_fields_set contains the field
        if self.client_id is None and "client_id" in self.model_fields_set:
            _dict['client_id'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if icon_url (nullable) is None
        # and model_fields_set contains the field
        if self.icon_url is None and "icon_url" in self.model_fields_set:
            _dict['icon_url'] = None

        # set to None if redirect_uri (nullable) is None
        # and model_fields_set contains the field
        if self.redirect_uri is None and "redirect_uri" in self.model_fields_set:
            _dict['redirect_uri'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OAuthClient from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "creator_user_id": obj.get("creator_user_id"),
            "updater_user_id": obj.get("updater_user_id"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "provider_key": obj.get("provider_key"),
            "client_id": obj.get("client_id"),
            "description": obj.get("description"),
            "icon_url": obj.get("icon_url"),
            "authorize_url": obj.get("authorize_url"),
            "token_url": obj.get("token_url"),
            "redirect_uri": obj.get("redirect_uri")
        })
        return _obj


