# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SettingsIn(BaseModel):
    """
    SettingsIn
    """ # noqa: E501
    guardrails_enabled: Optional[StrictBool] = None
    sharepoint_enabled: Optional[StrictBool] = None
    inbound_guardrail: Optional[StrictStr] = None
    outbound_guardrail: Optional[StrictStr] = None
    welcome_email_template_id: Optional[StrictInt] = None
    project_member_added_email_template_id: Optional[StrictInt] = None
    system_prompt: Optional[StrictStr] = None
    errlog_webhook_url: Optional[StrictStr] = None
    require_email_confirmation: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["guardrails_enabled", "sharepoint_enabled", "inbound_guardrail", "outbound_guardrail", "welcome_email_template_id", "project_member_added_email_template_id", "system_prompt", "errlog_webhook_url", "require_email_confirmation"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SettingsIn from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if guardrails_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.guardrails_enabled is None and "guardrails_enabled" in self.model_fields_set:
            _dict['guardrails_enabled'] = None

        # set to None if sharepoint_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.sharepoint_enabled is None and "sharepoint_enabled" in self.model_fields_set:
            _dict['sharepoint_enabled'] = None

        # set to None if inbound_guardrail (nullable) is None
        # and model_fields_set contains the field
        if self.inbound_guardrail is None and "inbound_guardrail" in self.model_fields_set:
            _dict['inbound_guardrail'] = None

        # set to None if outbound_guardrail (nullable) is None
        # and model_fields_set contains the field
        if self.outbound_guardrail is None and "outbound_guardrail" in self.model_fields_set:
            _dict['outbound_guardrail'] = None

        # set to None if welcome_email_template_id (nullable) is None
        # and model_fields_set contains the field
        if self.welcome_email_template_id is None and "welcome_email_template_id" in self.model_fields_set:
            _dict['welcome_email_template_id'] = None

        # set to None if project_member_added_email_template_id (nullable) is None
        # and model_fields_set contains the field
        if self.project_member_added_email_template_id is None and "project_member_added_email_template_id" in self.model_fields_set:
            _dict['project_member_added_email_template_id'] = None

        # set to None if system_prompt (nullable) is None
        # and model_fields_set contains the field
        if self.system_prompt is None and "system_prompt" in self.model_fields_set:
            _dict['system_prompt'] = None

        # set to None if errlog_webhook_url (nullable) is None
        # and model_fields_set contains the field
        if self.errlog_webhook_url is None and "errlog_webhook_url" in self.model_fields_set:
            _dict['errlog_webhook_url'] = None

        # set to None if require_email_confirmation (nullable) is None
        # and model_fields_set contains the field
        if self.require_email_confirmation is None and "require_email_confirmation" in self.model_fields_set:
            _dict['require_email_confirmation'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SettingsIn from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "guardrails_enabled": obj.get("guardrails_enabled"),
            "sharepoint_enabled": obj.get("sharepoint_enabled"),
            "inbound_guardrail": obj.get("inbound_guardrail"),
            "outbound_guardrail": obj.get("outbound_guardrail"),
            "welcome_email_template_id": obj.get("welcome_email_template_id"),
            "project_member_added_email_template_id": obj.get("project_member_added_email_template_id"),
            "system_prompt": obj.get("system_prompt"),
            "errlog_webhook_url": obj.get("errlog_webhook_url"),
            "require_email_confirmation": obj.get("require_email_confirmation")
        })
        return _obj


