# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TenantOut(BaseModel):
    """
    TenantOut
    """ # noqa: E501
    id: StrictInt
    created_at: datetime
    creator_user_id: Optional[StrictInt] = None
    name: StrictStr
    slug: StrictStr
    domain: Optional[StrictStr] = None
    timezone: StrictStr
    locale: StrictStr
    tarif_id: Optional[StrictInt] = None
    max_users: Optional[StrictInt] = None
    max_projects: Optional[StrictInt] = None
    display_name: Optional[StrictStr] = None
    motto: Optional[StrictStr] = None
    logo_url: Optional[StrictStr] = None
    square_logo_url: Optional[StrictStr] = None
    favicon_url: Optional[StrictStr] = None
    chat_square_logo_url: Optional[StrictStr] = None
    primary_color: Optional[StrictStr] = None
    secondary_color: Optional[StrictStr] = None
    theme: Optional[StrictStr] = None
    storage_limit_gb: Optional[StrictInt] = None
    api_rate_limit: Optional[StrictInt] = None
    state: Optional[StrictStr] = None
    upstream_tenant_id: Optional[StrictStr] = None
    upstream_oidc_issuer: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "created_at", "creator_user_id", "name", "slug", "domain", "timezone", "locale", "tarif_id", "max_users", "max_projects", "display_name", "motto", "logo_url", "square_logo_url", "favicon_url", "chat_square_logo_url", "primary_color", "secondary_color", "theme", "storage_limit_gb", "api_rate_limit", "state", "upstream_tenant_id", "upstream_oidc_issuer"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TenantOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if creator_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.creator_user_id is None and "creator_user_id" in self.model_fields_set:
            _dict['creator_user_id'] = None

        # set to None if domain (nullable) is None
        # and model_fields_set contains the field
        if self.domain is None and "domain" in self.model_fields_set:
            _dict['domain'] = None

        # set to None if tarif_id (nullable) is None
        # and model_fields_set contains the field
        if self.tarif_id is None and "tarif_id" in self.model_fields_set:
            _dict['tarif_id'] = None

        # set to None if max_users (nullable) is None
        # and model_fields_set contains the field
        if self.max_users is None and "max_users" in self.model_fields_set:
            _dict['max_users'] = None

        # set to None if max_projects (nullable) is None
        # and model_fields_set contains the field
        if self.max_projects is None and "max_projects" in self.model_fields_set:
            _dict['max_projects'] = None

        # set to None if display_name (nullable) is None
        # and model_fields_set contains the field
        if self.display_name is None and "display_name" in self.model_fields_set:
            _dict['display_name'] = None

        # set to None if motto (nullable) is None
        # and model_fields_set contains the field
        if self.motto is None and "motto" in self.model_fields_set:
            _dict['motto'] = None

        # set to None if logo_url (nullable) is None
        # and model_fields_set contains the field
        if self.logo_url is None and "logo_url" in self.model_fields_set:
            _dict['logo_url'] = None

        # set to None if square_logo_url (nullable) is None
        # and model_fields_set contains the field
        if self.square_logo_url is None and "square_logo_url" in self.model_fields_set:
            _dict['square_logo_url'] = None

        # set to None if favicon_url (nullable) is None
        # and model_fields_set contains the field
        if self.favicon_url is None and "favicon_url" in self.model_fields_set:
            _dict['favicon_url'] = None

        # set to None if chat_square_logo_url (nullable) is None
        # and model_fields_set contains the field
        if self.chat_square_logo_url is None and "chat_square_logo_url" in self.model_fields_set:
            _dict['chat_square_logo_url'] = None

        # set to None if primary_color (nullable) is None
        # and model_fields_set contains the field
        if self.primary_color is None and "primary_color" in self.model_fields_set:
            _dict['primary_color'] = None

        # set to None if secondary_color (nullable) is None
        # and model_fields_set contains the field
        if self.secondary_color is None and "secondary_color" in self.model_fields_set:
            _dict['secondary_color'] = None

        # set to None if theme (nullable) is None
        # and model_fields_set contains the field
        if self.theme is None and "theme" in self.model_fields_set:
            _dict['theme'] = None

        # set to None if storage_limit_gb (nullable) is None
        # and model_fields_set contains the field
        if self.storage_limit_gb is None and "storage_limit_gb" in self.model_fields_set:
            _dict['storage_limit_gb'] = None

        # set to None if api_rate_limit (nullable) is None
        # and model_fields_set contains the field
        if self.api_rate_limit is None and "api_rate_limit" in self.model_fields_set:
            _dict['api_rate_limit'] = None

        # set to None if state (nullable) is None
        # and model_fields_set contains the field
        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        # set to None if upstream_tenant_id (nullable) is None
        # and model_fields_set contains the field
        if self.upstream_tenant_id is None and "upstream_tenant_id" in self.model_fields_set:
            _dict['upstream_tenant_id'] = None

        # set to None if upstream_oidc_issuer (nullable) is None
        # and model_fields_set contains the field
        if self.upstream_oidc_issuer is None and "upstream_oidc_issuer" in self.model_fields_set:
            _dict['upstream_oidc_issuer'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TenantOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created_at": obj.get("created_at"),
            "creator_user_id": obj.get("creator_user_id"),
            "name": obj.get("name"),
            "slug": obj.get("slug"),
            "domain": obj.get("domain"),
            "timezone": obj.get("timezone"),
            "locale": obj.get("locale"),
            "tarif_id": obj.get("tarif_id"),
            "max_users": obj.get("max_users"),
            "max_projects": obj.get("max_projects"),
            "display_name": obj.get("display_name"),
            "motto": obj.get("motto"),
            "logo_url": obj.get("logo_url"),
            "square_logo_url": obj.get("square_logo_url"),
            "favicon_url": obj.get("favicon_url"),
            "chat_square_logo_url": obj.get("chat_square_logo_url"),
            "primary_color": obj.get("primary_color"),
            "secondary_color": obj.get("secondary_color"),
            "theme": obj.get("theme"),
            "storage_limit_gb": obj.get("storage_limit_gb"),
            "api_rate_limit": obj.get("api_rate_limit"),
            "state": obj.get("state"),
            "upstream_tenant_id": obj.get("upstream_tenant_id"),
            "upstream_oidc_issuer": obj.get("upstream_oidc_issuer")
        })
        return _obj


