# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.models.tenant_in import TenantIn

class TestTenantIn(unittest.TestCase):
    """TenantIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantIn:
        """Test TenantIn
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantIn`
        """
        model = TenantIn()
        if include_optional:
            return TenantIn(
                name = '',
                slug = '',
                domain = '',
                timezone = '',
                locale = '',
                tarif_id = 56,
                tarif_expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                max_users = 56,
                max_projects = 56,
                display_name = '',
                motto = '',
                logo_url = '',
                square_logo_url = '',
                favicon_url = '',
                chat_square_logo_url = '',
                primary_color = '',
                secondary_color = '',
                theme = '',
                storage_limit_gb = 56,
                api_rate_limit = 56,
                upstream_tenant_id = ''
            )
        else:
            return TenantIn(
                name = '',
                slug = '',
        )
        """

    def testTenantIn(self):
        """Test TenantIn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
