# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_add_library_to_project_projects_project_id_libraries_library_id_post(self) -> None:
        """Test case for add_library_to_project_projects_project_id_libraries_library_id_post

        Add Library To Project
        """
        pass

    def test_add_members_projects_project_id_members_post(self) -> None:
        """Test case for add_members_projects_project_id_members_post

        Add Members
        """
        pass

    def test_create_project_projects_post(self) -> None:
        """Test case for create_project_projects_post

        Create Project
        """
        pass

    def test_delete_member_projects_project_id_members_user_id_delete(self) -> None:
        """Test case for delete_member_projects_project_id_members_user_id_delete

        Delete Member
        """
        pass

    def test_delete_members_projects_project_id_members_delete(self) -> None:
        """Test case for delete_members_projects_project_id_members_delete

        Delete Members
        """
        pass

    def test_delete_project_projects_project_id_delete(self) -> None:
        """Test case for delete_project_projects_project_id_delete

        Delete Project
        """
        pass

    def test_is_project_name_free_projects_available_get(self) -> None:
        """Test case for is_project_name_free_projects_available_get

        Is Project Name Free
        """
        pass

    def test_leave_project_projects_project_id_remove_me_delete(self) -> None:
        """Test case for leave_project_projects_project_id_remove_me_delete

        Leave Project
        """
        pass

    def test_remove_library_from_project_projects_project_id_libraries_library_id_delete(self) -> None:
        """Test case for remove_library_from_project_projects_project_id_libraries_library_id_delete

        Remove Library From Project
        """
        pass

    def test_update_project_projects_project_id_patch(self) -> None:
        """Test case for update_project_projects_project_id_patch

        Update Project
        """
        pass


if __name__ == '__main__':
    unittest.main()
