# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.models.library_update_in import LibraryUpdateIn

class TestLibraryUpdateIn(unittest.TestCase):
    """LibraryUpdateIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LibraryUpdateIn:
        """Test LibraryUpdateIn
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LibraryUpdateIn`
        """
        model = LibraryUpdateIn()
        if include_optional:
            return LibraryUpdateIn(
                name = '',
                description = ''
            )
        else:
            return LibraryUpdateIn(
        )
        """

    def testLibraryUpdateIn(self):
        """Test LibraryUpdateIn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
