# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.api.template import Template


class TestTemplate(unittest.TestCase):
    """Template unit test stubs"""

    def setUp(self) -> None:
        self.api = Template()

    def tearDown(self) -> None:
        pass

    def test_templates_create(self) -> None:
        """Test case for templates_create

        Create
        """
        pass

    def test_templates_delete(self) -> None:
        """Test case for templates_delete

        Delete
        """
        pass

    def test_templates_update(self) -> None:
        """Test case for templates_update

        Update
        """
        pass


if __name__ == '__main__':
    unittest.main()
