# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.models.tariff_status_enum import TariffStatusEnum

class TestTariffStatusEnum(unittest.TestCase):
    """TariffStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTariffStatusEnum(self):
        """Test TariffStatusEnum"""
        # inst = TariffStatusEnum()

if __name__ == '__main__':
    unittest.main()
