# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.api.assistants_api import AssistantsApi


class TestAssistantsApi(unittest.TestCase):
    """AssistantsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssistantsApi()

    def tearDown(self) -> None:
        pass

    def test_add_library_to_assistant_assistants_assistant_id_libraries_library_id_post(self) -> None:
        """Test case for add_library_to_assistant_assistants_assistant_id_libraries_library_id_post

        Add Library To Assistant
        """
        pass

    def test_add_members_assistants_assistant_id_members_post(self) -> None:
        """Test case for add_members_assistants_assistant_id_members_post

        Add Members
        """
        pass

    def test_add_tool_to_assistant_assistants_assistant_id_tools_tool_id_post(self) -> None:
        """Test case for add_tool_to_assistant_assistants_assistant_id_tools_tool_id_post

        Add Tool To Assistant
        """
        pass

    def test_create_assistant_assistants_post(self) -> None:
        """Test case for create_assistant_assistants_post

        Create Assistant
        """
        pass

    def test_delete_assistant_assistants_assistant_id_delete(self) -> None:
        """Test case for delete_assistant_assistants_assistant_id_delete

        Delete Assistant
        """
        pass

    def test_delete_members_assistants_assistant_id_members_delete(self) -> None:
        """Test case for delete_members_assistants_assistant_id_members_delete

        Delete Members
        """
        pass

    def test_leave_assitant_assistants_assistant_id_remove_me_delete(self) -> None:
        """Test case for leave_assitant_assistants_assistant_id_remove_me_delete

        Leave Assitant
        """
        pass

    def test_remove_library_from_assistant_assistants_assistant_id_libraries_library_id_delete(self) -> None:
        """Test case for remove_library_from_assistant_assistants_assistant_id_libraries_library_id_delete

        Remove Library From Assistant
        """
        pass

    def test_remove_member_assistants_assistant_id_members_user_id_delete(self) -> None:
        """Test case for remove_member_assistants_assistant_id_members_user_id_delete

        Remove Member
        """
        pass

    def test_remove_tool_from_assistant_assistants_assistant_id_tools_tool_id_delete(self) -> None:
        """Test case for remove_tool_from_assistant_assistants_assistant_id_tools_tool_id_delete

        Remove Tool From Assistant
        """
        pass

    def test_submit_assistant_assistants_submit_post(self) -> None:
        """Test case for submit_assistant_assistants_submit_post

        Submit Assistant
        """
        pass

    def test_update_assistant_assistants_assistant_id_patch(self) -> None:
        """Test case for update_assistant_assistants_assistant_id_patch

        Update Assistant
        """
        pass


if __name__ == '__main__':
    unittest.main()
