# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.api.alert import Alert


class TestAlert(unittest.TestCase):
    """Alert unit test stubs"""

    def setUp(self) -> None:
        self.api = Alert()

    def tearDown(self) -> None:
        pass

    def test_alerts_create_alert(self) -> None:
        """Test case for alerts_create_alert

        Create Alert
        """
        pass

    def test_alerts_delete_alert(self) -> None:
        """Test case for alerts_delete_alert

        Delete Alert
        """
        pass

    def test_alerts_update_alert(self) -> None:
        """Test case for alerts_update_alert

        Update Alert
        """
        pass


if __name__ == '__main__':
    unittest.main()
