# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.api.templates_api import TemplatesApi


class TestTemplatesApi(unittest.TestCase):
    """TemplatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TemplatesApi()

    def tearDown(self) -> None:
        pass

    def test_create_templates_post(self) -> None:
        """Test case for create_templates_post

        Create
        """
        pass

    def test_delete_templates_template_id_delete(self) -> None:
        """Test case for delete_templates_template_id_delete

        Delete
        """
        pass

    def test_update_templates_template_id_patch(self) -> None:
        """Test case for update_templates_template_id_patch

        Update
        """
        pass


if __name__ == '__main__':
    unittest.main()
