# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_accept_invitation_complete_invitations_accept_post(self) -> None:
        """Test case for accept_invitation_complete_invitations_accept_post

        Accept Invitation Complete
        """
        pass

    def test_accept_invitation_form_invitations_accept_get(self) -> None:
        """Test case for accept_invitation_form_invitations_accept_get

        Accept Invitation Form
        """
        pass

    def test_activate_user_users_user_id_activate_post(self) -> None:
        """Test case for activate_user_users_user_id_activate_post

        Activate User
        """
        pass

    def test_add_library_member_libraries_library_id_members_post(self) -> None:
        """Test case for add_library_member_libraries_library_id_members_post

        Add Library Member
        """
        pass

    def test_add_library_to_assistant_assistants_assistant_id_libraries_library_id_post(self) -> None:
        """Test case for add_library_to_assistant_assistants_assistant_id_libraries_library_id_post

        Add Library To Assistant
        """
        pass

    def test_add_library_to_chat_chats_chat_id_libraries_library_id_post(self) -> None:
        """Test case for add_library_to_chat_chats_chat_id_libraries_library_id_post

        Add Library To Chat
        """
        pass

    def test_add_library_to_project_projects_project_id_libraries_library_id_post(self) -> None:
        """Test case for add_library_to_project_projects_project_id_libraries_library_id_post

        Add Library To Project
        """
        pass

    def test_add_library_to_tenants_tenants_tenant_id_libraries_library_id_post(self) -> None:
        """Test case for add_library_to_tenants_tenants_tenant_id_libraries_library_id_post

        Add Library To Tenants
        """
        pass

    def test_add_tool_to_assistant_assistants_assistant_id_tools_tool_id_post(self) -> None:
        """Test case for add_tool_to_assistant_assistants_assistant_id_tools_tool_id_post

        Add Tool To Assistant
        """
        pass

    def test_admin_document_detail_admin_documents_document_id_get(self) -> None:
        """Test case for admin_document_detail_admin_documents_document_id_get

        Admin Document Detail
        """
        pass

    def test_admin_embedding_admin_embedding_get(self) -> None:
        """Test case for admin_embedding_admin_embedding_get

        Admin Embedding
        """
        pass

    def test_admin_files_admin_files_get(self) -> None:
        """Test case for admin_files_admin_files_get

        Admin Files
        """
        pass

    def test_admin_health_live_admin_health_live_get(self) -> None:
        """Test case for admin_health_live_admin_health_live_get

        Admin Health Live
        """
        pass

    def test_admin_llm_admin_llm_get(self) -> None:
        """Test case for admin_llm_admin_llm_get

        Admin Llm
        """
        pass

    def test_admin_login_admin_login_post(self) -> None:
        """Test case for admin_login_admin_login_post

        Admin Login
        """
        pass

    def test_admin_login_page_admin_login_get(self) -> None:
        """Test case for admin_login_page_admin_login_get

        Admin Login Page
        """
        pass

    def test_admin_logout_get(self) -> None:
        """Test case for admin_logout_get

        Admin Logout
        """
        pass

    def test_admin_logout_post(self) -> None:
        """Test case for admin_logout_post

        Admin Logout
        """
        pass

    def test_admin_maintenance_admin_maintenance_get(self) -> None:
        """Test case for admin_maintenance_admin_maintenance_get

        Admin Maintenance
        """
        pass

    def test_admin_overview_admin_overview_get(self) -> None:
        """Test case for admin_overview_admin_overview_get

        Admin Overview
        """
        pass

    def test_admin_pipeline_documents_admin_pipeline_documents_get(self) -> None:
        """Test case for admin_pipeline_documents_admin_pipeline_documents_get

        Admin Pipeline Documents
        """
        pass

    def test_admin_pipeline_stages_admin_pipeline_stages_get(self) -> None:
        """Test case for admin_pipeline_stages_admin_pipeline_stages_get

        Admin Pipeline Stages
        """
        pass

    def test_admin_post_admin_post_get(self) -> None:
        """Test case for admin_post_admin_post_get

        Admin Post
        """
        pass

    def test_admin_postgres_admin_postgres_get(self) -> None:
        """Test case for admin_postgres_admin_postgres_get

        Admin Postgres
        """
        pass

    def test_admin_queues_admin_queues_get(self) -> None:
        """Test case for admin_queues_admin_queues_get

        Admin Queues
        """
        pass

    def test_admin_report_detail_admin_reports_report_id_get(self) -> None:
        """Test case for admin_report_detail_admin_reports_report_id_get

        Admin Report Detail
        """
        pass

    def test_admin_reports_admin_reports_get(self) -> None:
        """Test case for admin_reports_admin_reports_get

        Admin Reports
        """
        pass

    def test_admin_root_admin_get(self) -> None:
        """Test case for admin_root_admin_get

        Admin Root
        """
        pass

    def test_admin_security_admin_security_get(self) -> None:
        """Test case for admin_security_admin_security_get

        Admin Security
        """
        pass

    def test_admin_tasks_metrics_admin_metrics_get(self) -> None:
        """Test case for admin_tasks_metrics_admin_metrics_get

        Admin Tasks Metrics
        """
        pass

    def test_admin_tool_call_detail_admin_tool_calls_tool_call_id_get(self) -> None:
        """Test case for admin_tool_call_detail_admin_tool_calls_tool_call_id_get

        Admin Tool Call Detail
        """
        pass

    def test_admin_tool_detail_admin_tools_tool_id_get(self) -> None:
        """Test case for admin_tool_detail_admin_tools_tool_id_get

        Admin Tool Detail
        """
        pass

    def test_admin_trace_detail_admin_traces_trace_id_get(self) -> None:
        """Test case for admin_trace_detail_admin_traces_trace_id_get

        Admin Trace Detail
        """
        pass

    def test_admin_trace_lookup_admin_trace_get(self) -> None:
        """Test case for admin_trace_lookup_admin_trace_get

        Admin Trace Lookup
        """
        pass

    def test_admin_traces_admin_traces_get(self) -> None:
        """Test case for admin_traces_admin_traces_get

        Admin Traces
        """
        pass

    def test_admin_worker_detail_admin_workers_worker_name_get(self) -> None:
        """Test case for admin_worker_detail_admin_workers_worker_name_get

        Admin Worker Detail
        """
        pass

    def test_admin_workers_admin_workers_get(self) -> None:
        """Test case for admin_workers_admin_workers_get

        Admin Workers
        """
        pass

    def test_azure_entra_callback_auth_callback_azure_entra_get(self) -> None:
        """Test case for azure_entra_callback_auth_callback_azure_entra_get

        Azure Entra Callback
        """
        pass

    def test_cancel_message_chats_chat_id_cancel_post(self) -> None:
        """Test case for cancel_message_chats_chat_id_cancel_post

        Cancel Message
        """
        pass

    def test_chat_trace_admin_chat_chat_id_get(self) -> None:
        """Test case for chat_trace_admin_chat_chat_id_get

        Chat Trace
        """
        pass

    def test_confirm_email_auth_confirm_email_get(self) -> None:
        """Test case for confirm_email_auth_confirm_email_get

        Confirm Email
        """
        pass

    def test_convert_message_messages_message_id_convert_get(self) -> None:
        """Test case for convert_message_messages_message_id_convert_get

        Convert Message
        """
        pass

    def test_create_alert_alerts_post(self) -> None:
        """Test case for create_alert_alerts_post

        Create Alert
        """
        pass

    def test_create_app_applications_post(self) -> None:
        """Test case for create_app_applications_post

        Create App
        """
        pass

    def test_create_assistant_assistants_post(self) -> None:
        """Test case for create_assistant_assistants_post

        Create Assistant
        """
        pass

    def test_create_group_users_groups_post(self) -> None:
        """Test case for create_group_users_groups_post

        Create Group
        """
        pass

    def test_create_invitations_invitations_post(self) -> None:
        """Test case for create_invitations_invitations_post

        Create Invitations
        """
        pass

    def test_create_key_api_key_post(self) -> None:
        """Test case for create_key_api_key_post

        Create Key
        """
        pass

    def test_create_llm_model_llm_admin_models_post(self) -> None:
        """Test case for create_llm_model_llm_admin_models_post

        Create Llm Model
        """
        pass

    def test_create_member_assistants_assistant_id_members_user_id_post(self) -> None:
        """Test case for create_member_assistants_assistant_id_members_user_id_post

        Create Member
        """
        pass

    def test_create_member_projects_project_id_members_post(self) -> None:
        """Test case for create_member_projects_project_id_members_post

        Create Member
        """
        pass

    def test_create_message_messages_post(self) -> None:
        """Test case for create_message_messages_post

        Create Message
        """
        pass

    def test_create_project_projects_post(self) -> None:
        """Test case for create_project_projects_post

        Create Project
        """
        pass

    def test_create_prompt_prompts_post(self) -> None:
        """Test case for create_prompt_prompts_post

        Create Prompt
        """
        pass

    def test_create_tarif_tarifs_post(self) -> None:
        """Test case for create_tarif_tarifs_post

        Create Tarif
        """
        pass

    def test_create_templates_post(self) -> None:
        """Test case for create_templates_post

        Create
        """
        pass

    def test_create_tenant_connector_tenants_tenant_id_connectors_connector_id_post(self) -> None:
        """Test case for create_tenant_connector_tenants_tenant_id_connectors_connector_id_post

        Create Tenant Connector
        """
        pass

    def test_create_tenant_tenants_post(self) -> None:
        """Test case for create_tenant_tenants_post

        Create Tenant
        """
        pass

    def test_create_tenant_tool_tenants_tenant_id_tools_tool_id_post(self) -> None:
        """Test case for create_tenant_tool_tenants_tenant_id_tools_tool_id_post

        Create Tenant Tool
        """
        pass

    def test_create_user_users_post(self) -> None:
        """Test case for create_user_users_post

        Create User
        """
        pass

    def test_current_settings_current_get(self) -> None:
        """Test case for current_settings_current_get

        Current
        """
        pass

    def test_deactivate_documents_chats_chat_id_inactive_documents_post(self) -> None:
        """Test case for deactivate_documents_chats_chat_id_inactive_documents_post

        Deactivate Documents
        """
        pass

    def test_deactivate_user_users_user_id_deactivate_post(self) -> None:
        """Test case for deactivate_user_users_user_id_deactivate_post

        Deactivate User
        """
        pass

    def test_delete_alert_alerts_alert_id_delete(self) -> None:
        """Test case for delete_alert_alerts_alert_id_delete

        Delete Alert
        """
        pass

    def test_delete_app_applications_app_id_delete(self) -> None:
        """Test case for delete_app_applications_app_id_delete

        Delete App
        """
        pass

    def test_delete_assistant_assistants_assistant_id_delete(self) -> None:
        """Test case for delete_assistant_assistants_assistant_id_delete

        Delete Assistant
        """
        pass

    def test_delete_chat_document_documents_document_id_delete(self) -> None:
        """Test case for delete_chat_document_documents_document_id_delete

        Delete Chat Document
        """
        pass

    def test_delete_group_users_groups_group_id_delete(self) -> None:
        """Test case for delete_group_users_groups_group_id_delete

        Delete Group
        """
        pass

    def test_delete_library_libraries_library_id_delete(self) -> None:
        """Test case for delete_library_libraries_library_id_delete

        Delete Library
        """
        pass

    def test_delete_llm_model_llm_admin_models_model_id_delete(self) -> None:
        """Test case for delete_llm_model_llm_admin_models_model_id_delete

        Delete Llm Model
        """
        pass

    def test_delete_member_assistants_assistant_id_members_user_id_delete(self) -> None:
        """Test case for delete_member_assistants_assistant_id_members_user_id_delete

        Delete Member
        """
        pass

    def test_delete_member_projects_project_id_members_user_id_delete(self) -> None:
        """Test case for delete_member_projects_project_id_members_user_id_delete

        Delete Member
        """
        pass

    def test_delete_project_projects_project_id_delete(self) -> None:
        """Test case for delete_project_projects_project_id_delete

        Delete Project
        """
        pass

    def test_delete_prompt_prompts_prompt_id_delete(self) -> None:
        """Test case for delete_prompt_prompts_prompt_id_delete

        Delete Prompt
        """
        pass

    def test_delete_tarif_tarifs_tarif_id_delete(self) -> None:
        """Test case for delete_tarif_tarifs_tarif_id_delete

        Delete Tarif
        """
        pass

    def test_delete_templates_template_id_delete(self) -> None:
        """Test case for delete_templates_template_id_delete

        Delete
        """
        pass

    def test_delete_tenant_connector_tenants_tenant_id_connectors_connector_id_delete(self) -> None:
        """Test case for delete_tenant_connector_tenants_tenant_id_connectors_connector_id_delete

        Delete Tenant Connector
        """
        pass

    def test_delete_tenant_tenants_tenant_id_delete(self) -> None:
        """Test case for delete_tenant_tenants_tenant_id_delete

        Delete Tenant
        """
        pass

    def test_delete_tenant_tool_tenants_tenant_id_tools_tool_id_delete(self) -> None:
        """Test case for delete_tenant_tool_tenants_tenant_id_tools_tool_id_delete

        Delete Tenant Tool
        """
        pass

    def test_delete_user_users_user_id_delete(self) -> None:
        """Test case for delete_user_users_user_id_delete

        Delete User
        """
        pass

    def test_download_file_files_file_id_get(self) -> None:
        """Test case for download_file_files_file_id_get

        Download File
        """
        pass

    def test_download_file_storage_path_get(self) -> None:
        """Test case for download_file_storage_path_get

        Download File
        """
        pass

    def test_exchange_token_auth_exchange_token_post(self) -> None:
        """Test case for exchange_token_auth_exchange_token_post

        Exchange Token
        """
        pass

    def test_get_cost_llm_cost_post(self) -> None:
        """Test case for get_cost_llm_cost_post

        Get Cost
        """
        pass

    def test_get_current_tenant_tenants_current_get(self) -> None:
        """Test case for get_current_tenant_tenants_current_get

        Get Current Tenant
        """
        pass

    def test_get_entra_groups_auth_entra_groups_get(self) -> None:
        """Test case for get_entra_groups_auth_entra_groups_get

        Get Entra Groups
        """
        pass

    def test_get_entra_scopes_auth_entra_scopes_get(self) -> None:
        """Test case for get_entra_scopes_auth_entra_scopes_get

        Get Entra Scopes
        """
        pass

    def test_get_file_documents_document_id_get(self) -> None:
        """Test case for get_file_documents_document_id_get

        Get File
        """
        pass

    def test_get_item_info_integrations_sharepoint_drives_drive_id_items_drive_item_id_get(self) -> None:
        """Test case for get_item_info_integrations_sharepoint_drives_drive_id_items_drive_item_id_get

        Get Item Info
        """
        pass

    def test_get_myself_users_me_get(self) -> None:
        """Test case for get_myself_users_me_get

        Get Myself
        """
        pass

    def test_get_supported_languages_simple_chat_languages_get(self) -> None:
        """Test case for get_supported_languages_simple_chat_languages_get

        Get Supported Languages
        """
        pass

    def test_get_theme_theme_get(self) -> None:
        """Test case for get_theme_theme_get

        Get Theme
        """
        pass

    def test_get_usage_costs_llm_services_cost_post(self) -> None:
        """Test case for get_usage_costs_llm_services_cost_post

        Get Usage Costs
        """
        pass

    def test_get_user_info_integrations_sharepoint_me_get(self) -> None:
        """Test case for get_user_info_integrations_sharepoint_me_get

        Get User Info
        """
        pass

    def test_grant_tenant_model_access_llm_admin_tenants_tenant_id_models_model_id_post(self) -> None:
        """Test case for grant_tenant_model_access_llm_admin_tenants_tenant_id_models_model_id_post

        Grant Tenant Model Access
        """
        pass

    def test_import_documents_documents_import_post(self) -> None:
        """Test case for import_documents_documents_import_post

        Import Documents
        """
        pass

    def test_initiate_consent_auth_connectors_connector_id_consent_get(self) -> None:
        """Test case for initiate_consent_auth_connectors_connector_id_consent_get

        Initiate Consent
        """
        pass

    def test_is_connected_integrations_sharepoint_connected_get(self) -> None:
        """Test case for is_connected_integrations_sharepoint_connected_get

        Is Connected
        """
        pass

    def test_is_project_name_free_projects_available_get(self) -> None:
        """Test case for is_project_name_free_projects_available_get

        Is Project Name Free
        """
        pass

    def test_leave_assitant_assistants_assistant_id_remove_me_delete(self) -> None:
        """Test case for leave_assitant_assistants_assistant_id_remove_me_delete

        Leave Assitant
        """
        pass

    def test_leave_project_projects_project_id_remove_me_delete(self) -> None:
        """Test case for leave_project_projects_project_id_remove_me_delete

        Leave Project
        """
        pass

    def test_list_all_sites_integrations_sharepoint_sites_get(self) -> None:
        """Test case for list_all_sites_integrations_sharepoint_sites_get

        List All Sites
        """
        pass

    def test_list_available_models_settings_models_get(self) -> None:
        """Test case for list_available_models_settings_models_get

        List Available Models
        """
        pass

    def test_list_children_integrations_sharepoint_drives_drive_id_items_drive_item_id_children_get(self) -> None:
        """Test case for list_children_integrations_sharepoint_drives_drive_id_items_drive_item_id_children_get

        List Children
        """
        pass

    def test_list_connector_status_auth_connectors_status_get(self) -> None:
        """Test case for list_connector_status_auth_connectors_status_get

        List Connector Status
        """
        pass

    def test_list_drives_integrations_sharepoint_sites_site_id_drives_get(self) -> None:
        """Test case for list_drives_integrations_sharepoint_sites_site_id_drives_get

        List Drives
        """
        pass

    def test_llm_total_tokens_llm_tokens_post(self) -> None:
        """Test case for llm_total_tokens_llm_tokens_post

        Llm Total Tokens
        """
        pass

    def test_login_auth_token_post(self) -> None:
        """Test case for login_auth_token_post

        Login
        """
        pass

    def test_logout_auth_logout_post(self) -> None:
        """Test case for logout_auth_logout_post

        Logout
        """
        pass

    def test_message_trace_admin_message_message_id_get(self) -> None:
        """Test case for message_trace_admin_message_message_id_get

        Message Trace
        """
        pass

    def test_new_library_libraries_post(self) -> None:
        """Test case for new_library_libraries_post

        New Library
        """
        pass

    def test_oauth_callback_auth_connectors_callback_get(self) -> None:
        """Test case for oauth_callback_auth_connectors_callback_get

        Oauth Callback
        """
        pass

    def test_post_check_post_post(self) -> None:
        """Test case for post_check_post_post

        Post Check
        """
        pass

    def test_query_query_path_get(self) -> None:
        """Test case for query_query_path_get

        Query
        """
        pass

    def test_query_rpc_query_rpc_path_get(self) -> None:
        """Test case for query_rpc_query_rpc_path_get

        Query Rpc
        """
        pass

    def test_remove_chat_chats_chat_id_delete(self) -> None:
        """Test case for remove_chat_chats_chat_id_delete

        Remove Chat
        """
        pass

    def test_remove_inactive_documents_chats_chat_id_inactive_documents_delete(self) -> None:
        """Test case for remove_inactive_documents_chats_chat_id_inactive_documents_delete

        Remove Inactive Documents
        """
        pass

    def test_remove_library_from_assistant_assistants_assistant_id_libraries_library_id_delete(self) -> None:
        """Test case for remove_library_from_assistant_assistants_assistant_id_libraries_library_id_delete

        Remove Library From Assistant
        """
        pass

    def test_remove_library_from_chat_chats_chat_id_libraries_library_id_delete(self) -> None:
        """Test case for remove_library_from_chat_chats_chat_id_libraries_library_id_delete

        Remove Library From Chat
        """
        pass

    def test_remove_library_from_project_projects_project_id_libraries_library_id_delete(self) -> None:
        """Test case for remove_library_from_project_projects_project_id_libraries_library_id_delete

        Remove Library From Project
        """
        pass

    def test_remove_library_member_libraries_library_id_members_member_id_delete(self) -> None:
        """Test case for remove_library_member_libraries_library_id_members_member_id_delete

        Remove Library Member
        """
        pass

    def test_remove_tenant_library_member_tenants_tenant_id_libraries_library_id_delete(self) -> None:
        """Test case for remove_tenant_library_member_tenants_tenant_id_libraries_library_id_delete

        Remove Tenant Library Member
        """
        pass

    def test_remove_tool_from_assistant_assistants_assistant_id_tools_tool_id_delete(self) -> None:
        """Test case for remove_tool_from_assistant_assistants_assistant_id_tools_tool_id_delete

        Remove Tool From Assistant
        """
        pass

    def test_rephrase_message_messages_message_id_rephrase_get(self) -> None:
        """Test case for rephrase_message_messages_message_id_rephrase_get

        Rephrase Message
        """
        pass

    def test_reports_bulk_action_admin_reports_bulk_post(self) -> None:
        """Test case for reports_bulk_action_admin_reports_bulk_post

        Reports Bulk Action
        """
        pass

    def test_request_password_reset_auth_request_password_reset_post(self) -> None:
        """Test case for request_password_reset_auth_request_password_reset_post

        Request Password Reset
        """
        pass

    def test_resend_invitation_invitations_invitation_id_resend_post(self) -> None:
        """Test case for resend_invitation_invitations_invitation_id_resend_post

        Resend Invitation
        """
        pass

    def test_reset_password_auth_reset_password_post(self) -> None:
        """Test case for reset_password_auth_reset_password_post

        Reset Password
        """
        pass

    def test_reset_password_form_auth_reset_password_get(self) -> None:
        """Test case for reset_password_form_auth_reset_password_get

        Reset Password Form
        """
        pass

    def test_reset_password_users_passwd_post(self) -> None:
        """Test case for reset_password_users_passwd_post

        Reset Password
        """
        pass

    def test_retry_document_documents_document_id_retry_post(self) -> None:
        """Test case for retry_document_documents_document_id_retry_post

        Retry Document
        """
        pass

    def test_revoke_api_key_api_key_revoke_api_key_id_patch(self) -> None:
        """Test case for revoke_api_key_api_key_revoke_api_key_id_patch

        Revoke Api Key
        """
        pass

    def test_revoke_consent_auth_connectors_connector_id_consent_delete(self) -> None:
        """Test case for revoke_consent_auth_connectors_connector_id_consent_delete

        Revoke Consent
        """
        pass

    def test_revoke_invitation_invitations_invitation_id_revoke_post(self) -> None:
        """Test case for revoke_invitation_invitations_invitation_id_revoke_post

        Revoke Invitation
        """
        pass

    def test_revoke_tenant_model_access_llm_admin_tenants_tenant_id_models_model_id_delete(self) -> None:
        """Test case for revoke_tenant_model_access_llm_admin_tenants_tenant_id_models_model_id_delete

        Revoke Tenant Model Access
        """
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        Root
        """
        pass

    def test_send_email_confirmation_auth_send_email_confirmation_post(self) -> None:
        """Test case for send_email_confirmation_auth_send_email_confirmation_post

        Send Email Confirmation
        """
        pass

    def test_simple_chat_simple_chat_post(self) -> None:
        """Test case for simple_chat_simple_chat_post

        Simple Chat
        """
        pass

    def test_stat_stat_get(self) -> None:
        """Test case for stat_stat_get

        Stat
        """
        pass

    def test_submit_assistant_assistants_submit_post(self) -> None:
        """Test case for submit_assistant_assistants_submit_post

        Submit Assistant
        """
        pass

    def test_submit_message_messages_submit_post(self) -> None:
        """Test case for submit_message_messages_submit_post

        Submit Message
        """
        pass

    def test_summerize_chat_chats_chat_id_summary_get(self) -> None:
        """Test case for summerize_chat_chats_chat_id_summary_get

        Summerize Chat
        """
        pass

    def test_translate_message_messages_message_id_translate_get(self) -> None:
        """Test case for translate_message_messages_message_id_translate_get

        Translate Message
        """
        pass

    def test_unimport_documents_documents_import_delete(self) -> None:
        """Test case for unimport_documents_documents_import_delete

        Unimport Documents
        """
        pass

    def test_update_alert_alerts_alert_id_patch(self) -> None:
        """Test case for update_alert_alerts_alert_id_patch

        Update Alert
        """
        pass

    def test_update_app_applications_app_id_patch(self) -> None:
        """Test case for update_app_applications_app_id_patch

        Update App
        """
        pass

    def test_update_assistant_assistants_assistant_id_patch(self) -> None:
        """Test case for update_assistant_assistants_assistant_id_patch

        Update Assistant
        """
        pass

    def test_update_chat_chats_chat_id_patch(self) -> None:
        """Test case for update_chat_chats_chat_id_patch

        Update Chat
        """
        pass

    def test_update_chat_tool_settings_chats_chat_id_tools_tool_id_put(self) -> None:
        """Test case for update_chat_tool_settings_chats_chat_id_tools_tool_id_put

        Update Chat Tool Settings
        """
        pass

    def test_update_connector_auth_connectors_connector_id_patch(self) -> None:
        """Test case for update_connector_auth_connectors_connector_id_patch

        Update Connector
        """
        pass

    def test_update_current_settings_settings_current_patch(self) -> None:
        """Test case for update_current_settings_settings_current_patch

        Update Current Settings
        """
        pass

    def test_update_current_tenant_tenants_current_patch(self) -> None:
        """Test case for update_current_tenant_tenants_current_patch

        Update Current Tenant
        """
        pass

    def test_update_group_membership_applications_group_access_put(self) -> None:
        """Test case for update_group_membership_applications_group_access_put

        Update Group Membership
        """
        pass

    def test_update_group_users_groups_group_id_patch(self) -> None:
        """Test case for update_group_users_groups_group_id_patch

        Update Group
        """
        pass

    def test_update_library_libraries_library_id_patch(self) -> None:
        """Test case for update_library_libraries_library_id_patch

        Update Library
        """
        pass

    def test_update_llm_model_llm_admin_models_model_id_patch(self) -> None:
        """Test case for update_llm_model_llm_admin_models_model_id_patch

        Update Llm Model
        """
        pass

    def test_update_oauth_client_auth_connectors_oauth_clients_oauth_client_id_patch(self) -> None:
        """Test case for update_oauth_client_auth_connectors_oauth_clients_oauth_client_id_patch

        Update Oauth Client
        """
        pass

    def test_update_project_projects_project_id_patch(self) -> None:
        """Test case for update_project_projects_project_id_patch

        Update Project
        """
        pass

    def test_update_prompt_prompts_prompt_id_patch(self) -> None:
        """Test case for update_prompt_prompts_prompt_id_patch

        Update Prompt
        """
        pass

    def test_update_settings_settings_settings_id_patch(self) -> None:
        """Test case for update_settings_settings_settings_id_patch

        Update Settings
        """
        pass

    def test_update_system_settings_admin_system_settings_update_post(self) -> None:
        """Test case for update_system_settings_admin_system_settings_update_post

        Update System Settings
        """
        pass

    def test_update_tarif_tarifs_tarif_id_patch(self) -> None:
        """Test case for update_tarif_tarifs_tarif_id_patch

        Update Tarif
        """
        pass

    def test_update_templates_template_id_patch(self) -> None:
        """Test case for update_templates_template_id_patch

        Update
        """
        pass

    def test_update_tenant_tenants_tenant_id_patch(self) -> None:
        """Test case for update_tenant_tenants_tenant_id_patch

        Update Tenant
        """
        pass

    def test_update_tool_tools_tool_id_patch(self) -> None:
        """Test case for update_tool_tools_tool_id_patch

        Update Tool
        """
        pass

    def test_update_user_membership_applications_user_access_put(self) -> None:
        """Test case for update_user_membership_applications_user_access_put

        Update User Membership
        """
        pass

    def test_update_user_users_user_id_patch(self) -> None:
        """Test case for update_user_users_user_id_patch

        Update User
        """
        pass

    def test_upload_documents_documents_post(self) -> None:
        """Test case for upload_documents_documents_post

        Upload Documents
        """
        pass

    def test_upsert_members_users_members_group_id_put(self) -> None:
        """Test case for upsert_members_users_members_group_id_put

        Upsert Members
        """
        pass

    def test_upsert_my_preferences_users_me_preferences_patch(self) -> None:
        """Test case for upsert_my_preferences_users_me_preferences_patch

        Upsert My Preferences
        """
        pass

    def test_version_version_get(self) -> None:
        """Test case for version_version_get

        Version
        """
        pass


if __name__ == '__main__':
    unittest.main()
