"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import StrictBool, StrictInt, StrictStr
from typing import List, Optional
from neuland_hub_sdk.models.sharepoint_drive_model import SharepointDriveModel
from neuland_hub_sdk.models.sharepoint_item_model import SharepointItemModel
from neuland_hub_sdk.models.sharepoint_site_model import SharepointSiteModel

from neuland_hub_sdk.api_client import ApiClient, RequestSerialized
from neuland_hub_sdk.api_response import ApiResponse
from neuland_hub_sdk.rest import RESTResponseType


class Sharepoint:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def integrations_get_item_info(
        self,
        drive_id: StrictStr,
        drive_item_id: StrictStr,
        chat_id: Optional[StrictInt] = None,
        library_id: Optional[StrictInt] = None,
        assistant_id: Optional[StrictInt] = None,
        project_id: Optional[StrictInt] = None,
        cookie_name: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> SharepointItemModel:
        """Get Item Info


        :param drive_id: (required)
        :type drive_id: str
        :param drive_item_id: (required)
        :type drive_item_id: str
        :param chat_id:
        :type chat_id: int
        :param library_id:
        :type library_id: int
        :param assistant_id:
        :type assistant_id: int
        :param project_id:
        :type project_id: int
        :param cookie_name:
        :type cookie_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._integrations_get_item_info_serialize(
            drive_id=drive_id,
            drive_item_id=drive_item_id,
            chat_id=chat_id,
            library_id=library_id,
            assistant_id=assistant_id,
            project_id=project_id,
            cookie_name=cookie_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SharepointItemModel",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def integrations_get_item_info_with_http_info(
        self,
        drive_id: StrictStr,
        drive_item_id: StrictStr,
        chat_id: Optional[StrictInt] = None,
        library_id: Optional[StrictInt] = None,
        assistant_id: Optional[StrictInt] = None,
        project_id: Optional[StrictInt] = None,
        cookie_name: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[SharepointItemModel]:
        """Get Item Info


        :param drive_id: (required)
        :type drive_id: str
        :param drive_item_id: (required)
        :type drive_item_id: str
        :param chat_id:
        :type chat_id: int
        :param library_id:
        :type library_id: int
        :param assistant_id:
        :type assistant_id: int
        :param project_id:
        :type project_id: int
        :param cookie_name:
        :type cookie_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._integrations_get_item_info_serialize(
            drive_id=drive_id,
            drive_item_id=drive_item_id,
            chat_id=chat_id,
            library_id=library_id,
            assistant_id=assistant_id,
            project_id=project_id,
            cookie_name=cookie_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SharepointItemModel",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def integrations_get_item_info_without_preload_content(
        self,
        drive_id: StrictStr,
        drive_item_id: StrictStr,
        chat_id: Optional[StrictInt] = None,
        library_id: Optional[StrictInt] = None,
        assistant_id: Optional[StrictInt] = None,
        project_id: Optional[StrictInt] = None,
        cookie_name: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Item Info


        :param drive_id: (required)
        :type drive_id: str
        :param drive_item_id: (required)
        :type drive_item_id: str
        :param chat_id:
        :type chat_id: int
        :param library_id:
        :type library_id: int
        :param assistant_id:
        :type assistant_id: int
        :param project_id:
        :type project_id: int
        :param cookie_name:
        :type cookie_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._integrations_get_item_info_serialize(
            drive_id=drive_id,
            drive_item_id=drive_item_id,
            chat_id=chat_id,
            library_id=library_id,
            assistant_id=assistant_id,
            project_id=project_id,
            cookie_name=cookie_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SharepointItemModel",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _integrations_get_item_info_serialize(
        self,
        drive_id,
        drive_item_id,
        chat_id,
        library_id,
        assistant_id,
        project_id,
        cookie_name,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if drive_id is not None:
            _path_params['drive_id'] = drive_id
        if drive_item_id is not None:
            _path_params['drive_item_id'] = drive_item_id
        # process the query parameters
        if chat_id is not None:
            
            _query_params.append(('chat_id', chat_id))
            
        if library_id is not None:
            
            _query_params.append(('library_id', library_id))
            
        if assistant_id is not None:
            
            _query_params.append(('assistant_id', assistant_id))
            
        if project_id is not None:
            
            _query_params.append(('project_id', project_id))
            
        if cookie_name is not None:
            
            _query_params.append(('cookie_name', cookie_name))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'APIKeyHeader', 
            'OAuth2PasswordBearer'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/integrations/sharepoint/drives/{drive_id}/items/{drive_item_id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def integrations_list_all_sites(
        self,
        chat_id: Optional[StrictInt] = None,
        library_id: Optional[StrictInt] = None,
        assistant_id: Optional[StrictInt] = None,
        project_id: Optional[StrictInt] = None,
        cookie_name: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[SharepointSiteModel]:
        """List All Sites


        :param chat_id:
        :type chat_id: int
        :param library_id:
        :type library_id: int
        :param assistant_id:
        :type assistant_id: int
        :param project_id:
        :type project_id: int
        :param cookie_name:
        :type cookie_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._integrations_list_all_sites_serialize(
            chat_id=chat_id,
            library_id=library_id,
            assistant_id=assistant_id,
            project_id=project_id,
            cookie_name=cookie_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[SharepointSiteModel]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def integrations_list_all_sites_with_http_info(
        self,
        chat_id: Optional[StrictInt] = None,
        library_id: Optional[StrictInt] = None,
        assistant_id: Optional[StrictInt] = None,
        project_id: Optional[StrictInt] = None,
        cookie_name: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[SharepointSiteModel]]:
        """List All Sites


        :param chat_id:
        :type chat_id: int
        :param library_id:
        :type library_id: int
        :param assistant_id:
        :type assistant_id: int
        :param project_id:
        :type project_id: int
        :param cookie_name:
        :type cookie_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._integrations_list_all_sites_serialize(
            chat_id=chat_id,
            library_id=library_id,
            assistant_id=assistant_id,
            project_id=project_id,
            cookie_name=cookie_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[SharepointSiteModel]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def integrations_list_all_sites_without_preload_content(
        self,
        chat_id: Optional[StrictInt] = None,
        library_id: Optional[StrictInt] = None,
        assistant_id: Optional[StrictInt] = None,
        project_id: Optional[StrictInt] = None,
        cookie_name: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List All Sites


        :param chat_id:
        :type chat_id: int
        :param library_id:
        :type library_id: int
        :param assistant_id:
        :type assistant_id: int
        :param project_id:
        :type project_id: int
        :param cookie_name:
        :type cookie_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._integrations_list_all_sites_serialize(
            chat_id=chat_id,
            library_id=library_id,
            assistant_id=assistant_id,
            project_id=project_id,
            cookie_name=cookie_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[SharepointSiteModel]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _integrations_list_all_sites_serialize(
        self,
        chat_id,
        library_id,
        assistant_id,
        project_id,
        cookie_name,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if chat_id is not None:
            
            _query_params.append(('chat_id', chat_id))
            
        if library_id is not None:
            
            _query_params.append(('library_id', library_id))
            
        if assistant_id is not None:
            
            _query_params.append(('assistant_id', assistant_id))
            
        if project_id is not None:
            
            _query_params.append(('project_id', project_id))
            
        if cookie_name is not None:
            
            _query_params.append(('cookie_name', cookie_name))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'APIKeyHeader', 
            'OAuth2PasswordBearer'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/integrations/sharepoint/sites',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def integrations_list_children(
        self,
        drive_id: StrictStr,
        drive_item_id: StrictStr,
        chat_id: Optional[StrictInt] = None,
        library_id: Optional[StrictInt] = None,
        assistant_id: Optional[StrictInt] = None,
        project_id: Optional[StrictInt] = None,
        recursive: Optional[StrictBool] = None,
        cookie_name: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[SharepointItemModel]:
        """List Children


        :param drive_id: (required)
        :type drive_id: str
        :param drive_item_id: (required)
        :type drive_item_id: str
        :param chat_id:
        :type chat_id: int
        :param library_id:
        :type library_id: int
        :param assistant_id:
        :type assistant_id: int
        :param project_id:
        :type project_id: int
        :param recursive:
        :type recursive: bool
        :param cookie_name:
        :type cookie_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._integrations_list_children_serialize(
            drive_id=drive_id,
            drive_item_id=drive_item_id,
            chat_id=chat_id,
            library_id=library_id,
            assistant_id=assistant_id,
            project_id=project_id,
            recursive=recursive,
            cookie_name=cookie_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[SharepointItemModel]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def integrations_list_children_with_http_info(
        self,
        drive_id: StrictStr,
        drive_item_id: StrictStr,
        chat_id: Optional[StrictInt] = None,
        library_id: Optional[StrictInt] = None,
        assistant_id: Optional[StrictInt] = None,
        project_id: Optional[StrictInt] = None,
        recursive: Optional[StrictBool] = None,
        cookie_name: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[SharepointItemModel]]:
        """List Children


        :param drive_id: (required)
        :type drive_id: str
        :param drive_item_id: (required)
        :type drive_item_id: str
        :param chat_id:
        :type chat_id: int
        :param library_id:
        :type library_id: int
        :param assistant_id:
        :type assistant_id: int
        :param project_id:
        :type project_id: int
        :param recursive:
        :type recursive: bool
        :param cookie_name:
        :type cookie_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._integrations_list_children_serialize(
            drive_id=drive_id,
            drive_item_id=drive_item_id,
            chat_id=chat_id,
            library_id=library_id,
            assistant_id=assistant_id,
            project_id=project_id,
            recursive=recursive,
            cookie_name=cookie_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[SharepointItemModel]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def integrations_list_children_without_preload_content(
        self,
        drive_id: StrictStr,
        drive_item_id: StrictStr,
        chat_id: Optional[StrictInt] = None,
        library_id: Optional[StrictInt] = None,
        assistant_id: Optional[StrictInt] = None,
        project_id: Optional[StrictInt] = None,
        recursive: Optional[StrictBool] = None,
        cookie_name: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List Children


        :param drive_id: (required)
        :type drive_id: str
        :param drive_item_id: (required)
        :type drive_item_id: str
        :param chat_id:
        :type chat_id: int
        :param library_id:
        :type library_id: int
        :param assistant_id:
        :type assistant_id: int
        :param project_id:
        :type project_id: int
        :param recursive:
        :type recursive: bool
        :param cookie_name:
        :type cookie_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._integrations_list_children_serialize(
            drive_id=drive_id,
            drive_item_id=drive_item_id,
            chat_id=chat_id,
            library_id=library_id,
            assistant_id=assistant_id,
            project_id=project_id,
            recursive=recursive,
            cookie_name=cookie_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[SharepointItemModel]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _integrations_list_children_serialize(
        self,
        drive_id,
        drive_item_id,
        chat_id,
        library_id,
        assistant_id,
        project_id,
        recursive,
        cookie_name,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if drive_id is not None:
            _path_params['drive_id'] = drive_id
        if drive_item_id is not None:
            _path_params['drive_item_id'] = drive_item_id
        # process the query parameters
        if chat_id is not None:
            
            _query_params.append(('chat_id', chat_id))
            
        if library_id is not None:
            
            _query_params.append(('library_id', library_id))
            
        if assistant_id is not None:
            
            _query_params.append(('assistant_id', assistant_id))
            
        if project_id is not None:
            
            _query_params.append(('project_id', project_id))
            
        if recursive is not None:
            
            _query_params.append(('recursive', recursive))
            
        if cookie_name is not None:
            
            _query_params.append(('cookie_name', cookie_name))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'APIKeyHeader', 
            'OAuth2PasswordBearer'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/integrations/sharepoint/drives/{drive_id}/items/{drive_item_id}/children',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def integrations_list_drives(
        self,
        site_id: StrictStr,
        chat_id: Optional[StrictInt] = None,
        library_id: Optional[StrictInt] = None,
        assistant_id: Optional[StrictInt] = None,
        project_id: Optional[StrictInt] = None,
        cookie_name: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[SharepointDriveModel]:
        """List Drives


        :param site_id: (required)
        :type site_id: str
        :param chat_id:
        :type chat_id: int
        :param library_id:
        :type library_id: int
        :param assistant_id:
        :type assistant_id: int
        :param project_id:
        :type project_id: int
        :param cookie_name:
        :type cookie_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._integrations_list_drives_serialize(
            site_id=site_id,
            chat_id=chat_id,
            library_id=library_id,
            assistant_id=assistant_id,
            project_id=project_id,
            cookie_name=cookie_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[SharepointDriveModel]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def integrations_list_drives_with_http_info(
        self,
        site_id: StrictStr,
        chat_id: Optional[StrictInt] = None,
        library_id: Optional[StrictInt] = None,
        assistant_id: Optional[StrictInt] = None,
        project_id: Optional[StrictInt] = None,
        cookie_name: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[SharepointDriveModel]]:
        """List Drives


        :param site_id: (required)
        :type site_id: str
        :param chat_id:
        :type chat_id: int
        :param library_id:
        :type library_id: int
        :param assistant_id:
        :type assistant_id: int
        :param project_id:
        :type project_id: int
        :param cookie_name:
        :type cookie_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._integrations_list_drives_serialize(
            site_id=site_id,
            chat_id=chat_id,
            library_id=library_id,
            assistant_id=assistant_id,
            project_id=project_id,
            cookie_name=cookie_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[SharepointDriveModel]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def integrations_list_drives_without_preload_content(
        self,
        site_id: StrictStr,
        chat_id: Optional[StrictInt] = None,
        library_id: Optional[StrictInt] = None,
        assistant_id: Optional[StrictInt] = None,
        project_id: Optional[StrictInt] = None,
        cookie_name: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List Drives


        :param site_id: (required)
        :type site_id: str
        :param chat_id:
        :type chat_id: int
        :param library_id:
        :type library_id: int
        :param assistant_id:
        :type assistant_id: int
        :param project_id:
        :type project_id: int
        :param cookie_name:
        :type cookie_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._integrations_list_drives_serialize(
            site_id=site_id,
            chat_id=chat_id,
            library_id=library_id,
            assistant_id=assistant_id,
            project_id=project_id,
            cookie_name=cookie_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[SharepointDriveModel]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _integrations_list_drives_serialize(
        self,
        site_id,
        chat_id,
        library_id,
        assistant_id,
        project_id,
        cookie_name,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if site_id is not None:
            _path_params['site_id'] = site_id
        # process the query parameters
        if chat_id is not None:
            
            _query_params.append(('chat_id', chat_id))
            
        if library_id is not None:
            
            _query_params.append(('library_id', library_id))
            
        if assistant_id is not None:
            
            _query_params.append(('assistant_id', assistant_id))
            
        if project_id is not None:
            
            _query_params.append(('project_id', project_id))
            
        if cookie_name is not None:
            
            _query_params.append(('cookie_name', cookie_name))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'APIKeyHeader', 
            'OAuth2PasswordBearer'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/integrations/sharepoint/sites/{site_id}/drives',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


