# coding: utf-8

"""
    Neuland AI Hub API

    The **Neuland AI Hub API** powers chat, retrieval-augmented document Q&A, assistants, and the surrounding workspace, tenant, and integration features of the platform.  Most endpoints require authentication. Obtain a token via the **Auth** endpoints (or use an **ApiKey**) and send it as a bearer token in the `Authorization` header.  Endpoints are grouped by resource — see the tag groups below.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.models.assistant_catalog import AssistantCatalog

class TestAssistantCatalog(unittest.TestCase):
    """AssistantCatalog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssistantCatalog:
        """Test AssistantCatalog
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssistantCatalog`
        """
        model = AssistantCatalog()
        if include_optional:
            return AssistantCatalog(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                creator_user_id = 56,
                updater_user_id = 56,
                id = 56,
                public_id = '',
                name = '',
                description = '',
                avatar = '',
                instructions = '',
                llm_catalog_id = 56,
                temperature = 1.337,
                similarity_top_k = 56,
                version = '',
                state = 'ACTIVE',
                predefined_prompts = [
                    null
                    ]
            )
        else:
            return AssistantCatalog(
                name = '',
        )
        """

    def testAssistantCatalog(self):
        """Test AssistantCatalog"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
