# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.models.sharepoint_user_model import SharepointUserModel

class TestSharepointUserModel(unittest.TestCase):
    """SharepointUserModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SharepointUserModel:
        """Test SharepointUserModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SharepointUserModel`
        """
        model = SharepointUserModel()
        if include_optional:
            return SharepointUserModel(
                display_name = '',
                job_title = '',
                mail = '',
                surname = '',
                user_principal_name = ''
            )
        else:
            return SharepointUserModel(
                display_name = '',
                job_title = '',
                mail = '',
                surname = '',
                user_principal_name = '',
        )
        """

    def testSharepointUserModel(self):
        """Test SharepointUserModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
