# coding: utf-8

"""
    Neuland AI Hub API

    The **Neuland AI Hub API** powers chat, retrieval-augmented document Q&A, assistants, and the surrounding workspace, tenant, and integration features of the platform.  Most endpoints require authentication. Obtain a token via the **Auth** endpoints (or use an **ApiKey**) and send it as a bearer token in the `Authorization` header.  Endpoints are grouped by resource — see the tag groups below.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.models.application_in import ApplicationIn

class TestApplicationIn(unittest.TestCase):
    """ApplicationIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplicationIn:
        """Test ApplicationIn
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplicationIn`
        """
        model = ApplicationIn()
        if include_optional:
            return ApplicationIn(
                name = '',
                is_active = True,
                tenant_id = '',
                app_url = '',
                is_native = True,
                native_app_id = 56,
                description = '',
                version = '',
                avatar = ''
            )
        else:
            return ApplicationIn(
                name = '',
                tenant_id = '',
        )
        """

    def testApplicationIn(self):
        """Test ApplicationIn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
