# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.models.tarif_in import TarifIn

class TestTarifIn(unittest.TestCase):
    """TarifIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TarifIn:
        """Test TarifIn
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TarifIn`
        """
        model = TarifIn()
        if include_optional:
            return TarifIn(
                name = '',
                price = 1.337,
                hard_limit = 1.337,
                status = 'ACTIVE',
                expires_at = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                description = '',
                is_unlimited = True
            )
        else:
            return TarifIn(
                name = '',
                price = 1.337,
                hard_limit = 1.337,
        )
        """

    def testTarifIn(self):
        """Test TarifIn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
