# coding: utf-8

"""
    Neuland AI Hub API

    The **Neuland AI Hub API** powers chat, retrieval-augmented document Q&A, assistants, and the surrounding workspace, tenant, and integration features of the platform.  Most endpoints require authentication. Obtain a token via the **Auth** endpoints (or use an **ApiKey**) and send it as a bearer token in the `Authorization` header.  Endpoints are grouped by resource — see the tag groups below.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.models.sharepoint_site_model import SharepointSiteModel

class TestSharepointSiteModel(unittest.TestCase):
    """SharepointSiteModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SharepointSiteModel:
        """Test SharepointSiteModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SharepointSiteModel`
        """
        model = SharepointSiteModel()
        if include_optional:
            return SharepointSiteModel(
                id = '',
                web_url = '',
                name = '',
                display_name = '',
                description = '',
                imported_count = 56
            )
        else:
            return SharepointSiteModel(
                id = '',
                web_url = '',
                name = '',
                display_name = '',
                description = '',
        )
        """

    def testSharepointSiteModel(self):
        """Test SharepointSiteModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
