# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.api.default import Default


class TestDefault(unittest.TestCase):
    """Default unit test stubs"""

    def setUp(self) -> None:
        self.api = Default()

    def tearDown(self) -> None:
        pass

    def test_post_post_check(self) -> None:
        """Test case for post_post_check

        Post Check
        """
        pass

    def test_root_root(self) -> None:
        """Test case for root_root

        Root
        """
        pass

    def test_stat_stat(self) -> None:
        """Test case for stat_stat

        Stat
        """
        pass

    def test_theme_get_theme(self) -> None:
        """Test case for theme_get_theme

        Get Theme
        """
        pass

    def test_version_version(self) -> None:
        """Test case for version_version

        Version
        """
        pass


if __name__ == '__main__':
    unittest.main()
