# coding: utf-8

"""
    Neuland AI Hub API

    The **Neuland AI Hub API** powers chat, retrieval-augmented document Q&A, assistants, and the surrounding workspace, tenant, and integration features of the platform.  Most endpoints require authentication. Obtain a token via the **Auth** endpoints (or use an **ApiKey**) and send it as a bearer token in the `Authorization` header.  Endpoints are grouped by resource — see the tag groups below.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.models.assistant_in import AssistantIn

class TestAssistantIn(unittest.TestCase):
    """AssistantIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssistantIn:
        """Test AssistantIn
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssistantIn`
        """
        model = AssistantIn()
        if include_optional:
            return AssistantIn(
                name = '',
                model = '',
                avatar = '',
                description = '',
                description_show_in_chat = True,
                predefined_prompts = [
                    ''
                    ],
                instructions = '',
                temperature = 1.337,
                reasoning_effort = 'low',
                similarity_top_k = 1.337,
                input_type = 'prompt',
                form_fields = [
                    neuland_hub_sdk.models.form_field.FormField(
                        name = '', 
                        label = '', 
                        type = 'text', 
                        required = True, 
                        options = [
                            ''
                            ], 
                        placeholder = '', 
                        description = '', )
                    ]
            )
        else:
            return AssistantIn(
                name = '',
        )
        """

    def testAssistantIn(self):
        """Test AssistantIn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
