# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.api.llm import Llm


class TestLlm(unittest.TestCase):
    """Llm unit test stubs"""

    def setUp(self) -> None:
        self.api = Llm()

    def tearDown(self) -> None:
        pass

    def test_llm_get_cost(self) -> None:
        """Test case for llm_get_cost

        Get Cost
        """
        pass

    def test_llm_get_usage_costs(self) -> None:
        """Test case for llm_get_usage_costs

        Get Usage Costs
        """
        pass

    def test_llm_llm_total_tokens(self) -> None:
        """Test case for llm_llm_total_tokens

        Llm Total Tokens
        """
        pass


if __name__ == '__main__':
    unittest.main()
