# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.models.user_out import UserOut

class TestUserOut(unittest.TestCase):
    """UserOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserOut:
        """Test UserOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserOut`
        """
        model = UserOut()
        if include_optional:
            return UserOut(
                id = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                email = '',
                email_confirmed = True,
                pending_email = '',
                name = '',
                first_name = '',
                last_name = '',
                admin = True,
                superadmin = True,
                active = True,
                tenant_id = 56
            )
        else:
            return UserOut(
                id = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                email = '',
                email_confirmed = True,
                admin = True,
                active = True,
        )
        """

    def testUserOut(self):
        """Test UserOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
