# coding: utf-8

"""
    Neuland AI Hub API

    The **Neuland AI Hub API** powers chat, retrieval-augmented document Q&A, assistants, and the surrounding workspace, tenant, and integration features of the platform.  Most endpoints require authentication. Obtain a token via the **Auth** endpoints (or use an **ApiKey**) and send it as a bearer token in the `Authorization` header.  Endpoints are grouped by resource — see the tag groups below.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.models.usage_query_response import UsageQueryResponse

class TestUsageQueryResponse(unittest.TestCase):
    """UsageQueryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsageQueryResponse:
        """Test UsageQueryResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsageQueryResponse`
        """
        model = UsageQueryResponse()
        if include_optional:
            return UsageQueryResponse(
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                bucket = 'day',
                group_by = [
                    ''
                    ],
                totals = neuland_hub_sdk.models.usage_metrics.UsageMetrics(
                    cost = 1.337, 
                    total_tokens = 56, 
                    prompt_tokens = 56, 
                    completion_tokens = 56, 
                    requests = 56, ),
                rows = [
                    neuland_hub_sdk.models.usage_row.UsageRow(
                        cost = 1.337, 
                        total_tokens = 56, 
                        prompt_tokens = 56, 
                        completion_tokens = 56, 
                        requests = 56, 
                        group = {
                            'key' : null
                            }, 
                        bucket = '', )
                    ],
                truncated = True
            )
        else:
            return UsageQueryResponse(
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                bucket = 'day',
                group_by = [
                    ''
                    ],
                totals = neuland_hub_sdk.models.usage_metrics.UsageMetrics(
                    cost = 1.337, 
                    total_tokens = 56, 
                    prompt_tokens = 56, 
                    completion_tokens = 56, 
                    requests = 56, ),
                rows = [
                    neuland_hub_sdk.models.usage_row.UsageRow(
                        cost = 1.337, 
                        total_tokens = 56, 
                        prompt_tokens = 56, 
                        completion_tokens = 56, 
                        requests = 56, 
                        group = {
                            'key' : null
                            }, 
                        bucket = '', )
                    ],
        )
        """

    def testUsageQueryResponse(self):
        """Test UsageQueryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
