# coding: utf-8

"""
    Neuland AI Hub API

    The **Neuland AI Hub API** powers chat, retrieval-augmented document Q&A, assistants, and the surrounding workspace, tenant, and integration features of the platform.  Most endpoints require authentication. Obtain a token via the **Auth** endpoints (or use an **ApiKey**) and send it as a bearer token in the `Authorization` header.  Endpoints are grouped by resource — see the tag groups below.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.api.api_key import ApiKey


class TestApiKey(unittest.TestCase):
    """ApiKey unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiKey()

    def tearDown(self) -> None:
        pass

    def test_api_create_key(self) -> None:
        """Test case for api_create_key

        Create an API key
        """
        pass

    def test_api_revoke_api_key(self) -> None:
        """Test case for api_revoke_api_key

        Revoke an API key
        """
        pass


if __name__ == '__main__':
    unittest.main()
