# coding: utf-8

"""
    Neuland AI Hub API

    The **Neuland AI Hub API** powers chat, retrieval-augmented document Q&A, assistants, and the surrounding workspace, tenant, and integration features of the platform.  Most endpoints require authentication. Obtain a token via the **Auth** endpoints (or use an **ApiKey**) and send it as a bearer token in the `Authorization` header.  Endpoints are grouped by resource — see the tag groups below.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.api.tenant import Tenant


class TestTenant(unittest.TestCase):
    """Tenant unit test stubs"""

    def setUp(self) -> None:
        self.api = Tenant()

    def tearDown(self) -> None:
        pass

    def test_tenants_add_library_to_tenants(self) -> None:
        """Test case for tenants_add_library_to_tenants

        Assign a library to a tenant
        """
        pass

    def test_tenants_create_tenant(self) -> None:
        """Test case for tenants_create_tenant

        Create a tenant
        """
        pass

    def test_tenants_create_tenant_connector(self) -> None:
        """Test case for tenants_create_tenant_connector

        Enable a connector for a tenant
        """
        pass

    def test_tenants_create_tenant_oauth_client(self) -> None:
        """Test case for tenants_create_tenant_oauth_client

        Create Tenant Oauth Client
        """
        pass

    def test_tenants_create_tenant_tool(self) -> None:
        """Test case for tenants_create_tenant_tool

        Enable a tool for a tenant
        """
        pass

    def test_tenants_delete_tenant(self) -> None:
        """Test case for tenants_delete_tenant

        Delete a tenant
        """
        pass

    def test_tenants_delete_tenant_connector(self) -> None:
        """Test case for tenants_delete_tenant_connector

        Disable a connector for a tenant
        """
        pass

    def test_tenants_delete_tenant_model(self) -> None:
        """Test case for tenants_delete_tenant_model

        Disable a model for a tenant
        """
        pass

    def test_tenants_delete_tenant_models_bulk(self) -> None:
        """Test case for tenants_delete_tenant_models_bulk

        Disable a model for multiple tenants
        """
        pass

    def test_tenants_delete_tenant_oauth_client(self) -> None:
        """Test case for tenants_delete_tenant_oauth_client

        Delete Tenant Oauth Client
        """
        pass

    def test_tenants_delete_tenant_tool(self) -> None:
        """Test case for tenants_delete_tenant_tool

        Disable a tool for a tenant
        """
        pass

    def test_tenants_get_current_tenant(self) -> None:
        """Test case for tenants_get_current_tenant

        Get current tenant
        """
        pass

    def test_tenants_put_tenant_model(self) -> None:
        """Test case for tenants_put_tenant_model

        Enable a model for a tenant
        """
        pass

    def test_tenants_put_tenant_models_bulk(self) -> None:
        """Test case for tenants_put_tenant_models_bulk

        Enable a model for multiple tenants
        """
        pass

    def test_tenants_remove_tenant_library_member(self) -> None:
        """Test case for tenants_remove_tenant_library_member

        Unassign a library from a tenant
        """
        pass

    def test_tenants_update_current_tenant(self) -> None:
        """Test case for tenants_update_current_tenant

        Update current tenant
        """
        pass

    def test_tenants_update_tenant(self) -> None:
        """Test case for tenants_update_tenant

        Update a tenant
        """
        pass

    def test_tenants_update_tenant_oauth_client(self) -> None:
        """Test case for tenants_update_tenant_oauth_client

        Update Tenant Oauth Client
        """
        pass

    def test_tenants_update_tenant_oauth_secret(self) -> None:
        """Test case for tenants_update_tenant_oauth_secret

        Update Tenant Oauth Secret
        """
        pass


if __name__ == '__main__':
    unittest.main()
