# coding: utf-8

"""
    Neuland AI Hub API

    The **Neuland AI Hub API** powers chat, retrieval-augmented document Q&A, assistants, and the surrounding workspace, tenant, and integration features of the platform.  Most endpoints require authentication. Obtain a token via the **Auth** endpoints (or use an **ApiKey**) and send it as a bearer token in the `Authorization` header.  Endpoints are grouped by resource — see the tag groups below.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.api.sharepoint import Sharepoint


class TestSharepoint(unittest.TestCase):
    """Sharepoint unit test stubs"""

    def setUp(self) -> None:
        self.api = Sharepoint()

    def tearDown(self) -> None:
        pass

    def test_integrations_get_item_info(self) -> None:
        """Test case for integrations_get_item_info

        Get a drive item
        """
        pass

    def test_integrations_get_user_info(self) -> None:
        """Test case for integrations_get_user_info

        Get current SharePoint user
        """
        pass

    def test_integrations_is_connected(self) -> None:
        """Test case for integrations_is_connected

        Check SharePoint connection
        """
        pass

    def test_integrations_list_all_sites(self) -> None:
        """Test case for integrations_list_all_sites

        List SharePoint sites
        """
        pass

    def test_integrations_list_children(self) -> None:
        """Test case for integrations_list_children

        List children of a drive item
        """
        pass

    def test_integrations_list_drives(self) -> None:
        """Test case for integrations_list_drives

        List drives in a site
        """
        pass


if __name__ == '__main__':
    unittest.main()
