# coding: utf-8

"""
    Neuland AI Hub API

    The **Neuland AI Hub API** powers chat, retrieval-augmented document Q&A, assistants, and the surrounding workspace, tenant, and integration features of the platform.  Most endpoints require authentication. Obtain a token via the **Auth** endpoints (or use an **ApiKey**) and send it as a bearer token in the `Authorization` header.  Endpoints are grouped by resource — see the tag groups below.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.models.data_source_drive_model import DataSourceDriveModel

class TestDataSourceDriveModel(unittest.TestCase):
    """DataSourceDriveModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataSourceDriveModel:
        """Test DataSourceDriveModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataSourceDriveModel`
        """
        model = DataSourceDriveModel()
        if include_optional:
            return DataSourceDriveModel(
                id = '',
                web_url = '',
                name = '',
                description = '',
                root = neuland_hub_sdk.models.data_source_item_model.DataSourceItemModel(
                    id = '', 
                    web_url = '', 
                    drive_id = '', 
                    site_id = '', 
                    parent_folder_id = '', 
                    parent_path = '', 
                    name = '', 
                    description = '', 
                    size = 56, 
                    last_modified_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    mimetype = '', 
                    folder = null, 
                    imported = True, 
                    imported_count = 56, ),
                imported_count = 56
            )
        else:
            return DataSourceDriveModel(
                id = '',
                web_url = '',
                name = '',
                description = '',
                root = neuland_hub_sdk.models.data_source_item_model.DataSourceItemModel(
                    id = '', 
                    web_url = '', 
                    drive_id = '', 
                    site_id = '', 
                    parent_folder_id = '', 
                    parent_path = '', 
                    name = '', 
                    description = '', 
                    size = 56, 
                    last_modified_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    mimetype = '', 
                    folder = null, 
                    imported = True, 
                    imported_count = 56, ),
        )
        """

    def testDataSourceDriveModel(self):
        """Test DataSourceDriveModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
