# coding: utf-8

"""
    Neuland AI Hub API

    The **Neuland AI Hub API** powers chat, retrieval-augmented document Q&A, assistants, and the surrounding workspace, tenant, and integration features of the platform.  Most endpoints require authentication. Obtain a token via the **Auth** endpoints (or use an **ApiKey**) and send it as a bearer token in the `Authorization` header.  Endpoints are grouped by resource — see the tag groups below.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuland_hub_sdk.api.auth import Auth


class TestAuth(unittest.TestCase):
    """Auth unit test stubs"""

    def setUp(self) -> None:
        self.api = Auth()

    def tearDown(self) -> None:
        pass

    def test_auth_confirm_email(self) -> None:
        """Test case for auth_confirm_email

        Confirm an email address
        """
        pass

    def test_auth_exchange_token(self) -> None:
        """Test case for auth_exchange_token

        Exchange for a service token
        """
        pass

    def test_auth_get_entra_groups(self) -> None:
        """Test case for auth_get_entra_groups

        Get Entra group names
        """
        pass

    def test_auth_get_entra_scopes(self) -> None:
        """Test case for auth_get_entra_scopes

        List Entra scopes
        """
        pass

    def test_auth_login(self) -> None:
        """Test case for auth_login

        Log in
        """
        pass

    def test_auth_logout(self) -> None:
        """Test case for auth_logout

        Log out
        """
        pass

    def test_auth_request_password_reset(self) -> None:
        """Test case for auth_request_password_reset

        Request a password reset
        """
        pass

    def test_auth_reset_password(self) -> None:
        """Test case for auth_reset_password

        Complete a password reset
        """
        pass

    def test_auth_reset_password_form(self) -> None:
        """Test case for auth_reset_password_form

        Password reset HTML form
        """
        pass

    def test_auth_search_entra_groups(self) -> None:
        """Test case for auth_search_entra_groups

        Search Entra Groups
        """
        pass

    def test_auth_send_email_confirmation(self) -> None:
        """Test case for auth_send_email_confirmation

        Send an email confirmation
        """
        pass

    def test_auth_sso_exchange(self) -> None:
        """Test case for auth_sso_exchange

        Sso Exchange
        """
        pass

    def test_auth_sso_init(self) -> None:
        """Test case for auth_sso_init

        Sso Init
        """
        pass

    def test_auth_sso_resolve(self) -> None:
        """Test case for auth_sso_resolve

        Sso Resolve
        """
        pass


if __name__ == '__main__':
    unittest.main()
