# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ApplicationIn(BaseModel):
    """
    Schema for creating an application
    """ # noqa: E501
    name: StrictStr
    is_active: Optional[StrictBool] = True
    tenant_id: StrictInt
    app_url: Optional[StrictStr] = None
    is_native: Optional[StrictBool] = None
    native_app_id: Optional[StrictInt] = None
    description: Optional[StrictStr] = None
    version: Optional[StrictStr] = None
    avatar: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["name", "is_active", "tenant_id", "app_url", "is_native", "native_app_id", "description", "version", "avatar"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApplicationIn from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if app_url (nullable) is None
        # and model_fields_set contains the field
        if self.app_url is None and "app_url" in self.model_fields_set:
            _dict['app_url'] = None

        # set to None if is_native (nullable) is None
        # and model_fields_set contains the field
        if self.is_native is None and "is_native" in self.model_fields_set:
            _dict['is_native'] = None

        # set to None if native_app_id (nullable) is None
        # and model_fields_set contains the field
        if self.native_app_id is None and "native_app_id" in self.model_fields_set:
            _dict['native_app_id'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if version (nullable) is None
        # and model_fields_set contains the field
        if self.version is None and "version" in self.model_fields_set:
            _dict['version'] = None

        # set to None if avatar (nullable) is None
        # and model_fields_set contains the field
        if self.avatar is None and "avatar" in self.model_fields_set:
            _dict['avatar'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApplicationIn from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "is_active": obj.get("is_active") if obj.get("is_active") is not None else True,
            "tenant_id": obj.get("tenant_id"),
            "app_url": obj.get("app_url"),
            "is_native": obj.get("is_native"),
            "native_app_id": obj.get("native_app_id"),
            "description": obj.get("description"),
            "version": obj.get("version"),
            "avatar": obj.get("avatar")
        })
        return _obj


