# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from neuland_hub_sdk.models.timeseries_point import TimeseriesPoint
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TimeseriesResponse(BaseModel):
    """
    Timeseries response model for LLM costs. Contains total cost for the current month and timeseries data for each model.
    """ # noqa: E501
    total_cost: Union[StrictFloat, StrictInt]
    timeseries: Dict[str, List[TimeseriesPoint]]
    __properties: ClassVar[List[str]] = ["total_cost", "timeseries"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TimeseriesResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in timeseries (dict of array)
        _field_dict_of_array = {}
        if self.timeseries:
            for _key_timeseries in self.timeseries:
                if self.timeseries[_key_timeseries] is not None:
                    _field_dict_of_array[_key_timeseries] = [
                        _item.to_dict() for _item in self.timeseries[_key_timeseries]
                    ]
            _dict['timeseries'] = _field_dict_of_array
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TimeseriesResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total_cost": obj.get("total_cost"),
            "timeseries": dict(
                (_k,
                        [TimeseriesPoint.from_dict(_item) for _item in _v]
                        if _v is not None
                        else None
                )
                for _k, _v in obj.get("timeseries", {}).items()
            )
        })
        return _obj


